# exam_id -> (source_page_url, verb_pdf, kvant_pdf)
# source_page_url is the human-facing studera.nu index page (per-sitting).
B = "https://www.studera.nu"
G = B + "/globalassets/05-hogskoleprovet"

MANIFEST = {
    "var-2013": (f"{B}/hogskoleprov/fpn/normeringstabeller-varen-2013/",
                 f"{G}/normeringstabeller/norm13a_verb.pdf", f"{G}/normeringstabeller/norm13a_kvant.pdf"),
    "host-2013": (f"{B}/hogskoleprov/fpn/normeringstabeller-hosten-2013/",
                  f"{G}/normeringstabeller/norm13b_verb.pdf", f"{G}/normeringstabeller/norm13b_kvant.pdf"),
    "var-2014": (f"{B}/hogskoleprov/fpn/normeringstabeller-varen-2014/",
                 f"{G}/normeringstabeller/norm14a_verb.pdf", f"{G}/normeringstabeller/norm14a_kvant.pdf"),
    "host-2014": (f"{B}/hogskoleprov/fpn/normeringstabell-hosten-2014/",
                  f"{G}/normeringstabeller/norm14b_verb.pdf", f"{G}/normeringstabeller/norm14b_kvant.pdf"),
    "var-2015": (f"{B}/hogskoleprov/fpn/normeringstabeller-varen-2015/",
                 f"{G}/normeringstabeller/norm15a_verb.pdf", f"{G}/normeringstabeller/norm15a_kvant.pdf"),
    "host-2015": (f"{B}/hogskoleprov/fpn/normeringstabeller-hosten-2015/",
                  f"{G}/normeringstabeller/norm15b_verb.pdf", f"{G}/normeringstabeller/norm15b_kvant.pdf"),
    "var-2016": (f"{B}/hogskoleprov/fpn/normeringstabeller-varen-2016/",
                 f"{G}/normeringstabeller/norm-16a_verb.pdf", f"{G}/normeringstabeller/norm-16a_kvant.pdf"),
    "host-2016": (f"{B}/hogskoleprov/fpn/normeringstabeller-hosten-20162/",
                  f"{G}/normeringstabeller/normering-ht-2016/norm_16b_verb.pdf", f"{G}/normeringstabeller/normering-ht-2016/norm_16b_kvant.pdf"),
    "var-2017": (f"{B}/hogskoleprov/fpn/normeringstabellervt2017/",
                 f"{G}/normeringstabeller/normering-vt-2017/norm17a_verb.pdf", f"{G}/normeringstabeller/normering-vt-2017/norm17a_kvant.pdf"),
    "host-2017": (f"{B}/hogskoleprov/fpn/normeringstabeller-hosten-2017/",
                  f"{G}/normeringstabeller/normering-ht-2017/norm17b_verb.pdf", f"{G}/normeringstabeller/normering-ht-2017/norm17b_kvant.pdf"),
    "var-2018-1": (f"{B}/hogskoleprov/fpn/normeringstabeller-varen-2018/",
                   f"{G}/normeringstabeller/normering-vt-2018/norm18a_verb.pdf", f"{G}/normeringstabeller/normering-vt-2018/norm18a_kvant.pdf"),
    "host-2018": (f"{B}/hogskoleprov/fpn/normeringstabeller-hosten-2018/",
                  f"{G}/normeringstabeller/normering-ht-2018/norm18b_verb.pdf", f"{G}/normeringstabeller/normering-ht-2018/norm18b_kvant.pdf"),
    "var-2019": (f"{B}/hogskoleprov/fpn/normeringstabeller-varen-2019/",
                 f"{G}/normeringstabeller/normering-vt-2019/norm19a_verb.pdf", f"{G}/normeringstabeller/normering-vt-2019/norm19a_kvant.pdf"),
    # host-2019 had two quant versions (v1/v2), shared verbal -> maps to host-ver1/ver2-2019
    "host-ver1-2019": (f"{B}/hogskoleprov/fpn/normeringstabeller-hosten-2019/",
                       f"{G}/normeringstabeller/normering-ht-2019/norm19b_verb.pdf", f"{G}/normeringstabeller/normering-ht-2019/norm19b_kvant_v1.pdf"),
    "host-ver2-2019": (f"{B}/hogskoleprov/fpn/normeringstabeller-hosten-2019/",
                       f"{G}/normeringstabeller/normering-ht-2019/norm19b_verb.pdf", f"{G}/normeringstabeller/normering-ht-2019/norm19b_kvant_v2.pdf"),
    "host-2020": (f"{B}/hogskoleprov/fpn/normeringstabeller-hosten-2020/",
                  f"{G}/normeringstabeller/normering-ht-2020/norm20b_verb.pdf", f"{G}/normeringstabeller/normering-ht-2020/norm20b_kvant.pdf"),
    "host-2021": (f"{B}/hogskoleprov/fpn/normeringstabeller-hosten-2021/",
                  f"{G}/normeringstabeller/normering-ht-2021/norm21b_verb.pdf", f"{G}/normeringstabeller/normering-ht-2021/norm21b_kvant.pdf"),
    # var-2022 two sittings: 12 mars (a1) and 7 maj (a2)
    "var-2022-1": (f"{B}/hogskoleprov/fpn/normeringstabeller-varen-2022-12-mars/",
                   f"{G}/normeringstabeller/normering-vt-2022-12-mars/norm22a1_verb.pdf", f"{G}/normeringstabeller/normering-vt-2022-12-mars/norm22a1_kvant.pdf"),
    "var-2022-2": (f"{B}/hogskoleprov/fpn/normeringstabeller-varen-2022-7-maj/",
                   f"{G}/normeringstabeller/normering-vt2022-7-maj/norm22a2_verb.pdf", f"{G}/normeringstabeller/normering-vt2022-7-maj/norm22a2_kvant.pdf"),
    "host-2022": (f"{B}/hogskoleprov/fpn/normeringstabeller-hosten-2022/",
                  f"{G}/normeringstabeller/normering-ht2022/norm22b_verb.pdf", f"{G}/normeringstabeller/normering-ht2022/norm22b_kvant.pdf"),
    "var-2023": (f"{B}/hogskoleprov/fpn/normeringstabeller-varen-2023/",
                 f"{G}/normeringstabeller/normering-vt-2023-25-mars/norm23a_verb.pdf", f"{G}/normeringstabeller/normering-vt-2023-25-mars/norm23a_kvant.pdf"),
    "host-2023": (f"{B}/hogskoleprov/fpn/normeringstabeller-hosten-20232/",
                  f"{G}/hp-2023-10-22/norm23b_verb.pdf", f"{G}/hp-2023-10-22/norm23b_kvant.pdf"),
    "var-2024": (f"{B}/hogskoleprov/fpn/normeringstabeller-varen-2024/",
                 f"{G}/normeringstabeller/normering-vt2024-13-april/norm24a_verb.pdf", f"{G}/normeringstabeller/normering-vt2024-13-april/norm24a_kvant.pdf"),
    "host-2024": (f"{B}/hogskoleprov/fpn/normeringstabeller-hosten-2024/",
                  f"{G}/normeringstabeller/normering-ht2024-20-oktober/norm24b_verb.pdf", f"{G}/normeringstabeller/normering-ht2024-20-oktober/norm24b_kvant.pdf"),
    "var-2025": (f"{B}/hogskoleprov/fpn/normeringstabeller-varen-2025/",
                 f"{G}/normeringstabeller/normering-vt2025-5-april/norm25a_verb.pdf", f"{G}/normeringstabeller/normering-vt2025-5-april/norm25a_kvant.pdf"),
    "host-2025": (f"{B}/hogskoleprov/fpn/provfragor-facit-och-normering-hosten-2025/",
                  f"{G}/normeringstabeller/normering-ht2025-19-oktober/norm25b_verb.pdf", f"{G}/normeringstabeller/normering-ht2025-19-oktober/norm25b_kvant.pdf"),
    "var-2026": (f"{B}/hogskoleprov/fpn/",
                 f"{G}/normeringstabeller/normering-vt2026-18-april/norm26a_verb.pdf", f"{G}/normeringstabeller/normering-vt2026-18-april/norm26a_kvant.pdf"),
}
