import { ClerkProvider } from '@clerk/clerk-react'
import { QueryClientProvider } from '@tanstack/react-query'
import { createRouter, RouterProvider } from '@tanstack/react-router'
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'

import { queryClient } from './api/queryClient'
import { loadBank, type Question } from './data/questions'
import './index.css'
// KaTeX CSS — ships once globally so any <InlineMath> in the tree
// can render without per-component-style imports.
import 'katex/dist/katex.min.css'
import { routeTree } from './routeTree.gen'

// Pre-warm the question bank as soon as the SPA boots. The fetch runs
// in parallel with React mounting + Clerk handshaking, so by the time
// the user clicks "Starta övning" the bank is almost always already
// in memory. loadBank() is idempotent — anyone who calls it later
// shares the same Promise.
//
// We also expose the resolved bank on `window.__HPC_BANK__` so the
// Playwright e2e suite can resolve the correct answer for the rendered
// prompt without hard-coding it. The dataset is publicly served under
// /data/, so this isn't leaking anything.
loadBank().then((bank) => {
  ;(window as unknown as { __HPC_BANK__: readonly Question[] }).__HPC_BANK__ = bank
})

// `routeTree.gen.ts` is auto-generated by @tanstack/router-plugin from the
// files in src/routes. Don't edit it; the plugin rewrites it on every dev
// run and on `pnpm build`.
const router = createRouter({
  routeTree,
  // Default search-param parser; safe in case any route uses `?dev=1`.
  defaultPreload: 'intent',
})

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

const PUBLISHABLE_KEY = import.meta.env.VITE_CLERK_PUBLISHABLE_KEY as string | undefined
if (!PUBLISHABLE_KEY) {
  throw new Error(
    'Missing VITE_CLERK_PUBLISHABLE_KEY — copy app/.env.example to .env.local and set it',
  )
}

const rootEl = document.getElementById('root')
if (!rootEl) throw new Error('Missing #root element in index.html')

createRoot(rootEl).render(
  <StrictMode>
    <ClerkProvider
      publishableKey={PUBLISHABLE_KEY}
      // Map Clerk's redirects to TanStack Router routes so all auth
      // navigations stay inside our SPA shell.
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
      signInFallbackRedirectUrl="/"
      signUpFallbackRedirectUrl="/"
    >
      <QueryClientProvider client={queryClient}>
        <RouterProvider router={router} />
      </QueryClientProvider>
    </ClerkProvider>
  </StrictMode>,
)
