import { registerSW } from 'virtual:pwa-register'
import { ClerkProvider, useAuth } from '@clerk/clerk-react'
import { svSE } from '@clerk/localizations'
import { QueryClientProvider } from '@tanstack/react-query'
import { createRouter, RouterProvider } from '@tanstack/react-router'
import { MotionConfig } from 'motion/react'
import { StrictMode, useEffect } from 'react'
import { createRoot } from 'react-dom/client'
import { queryClient } from './api/queryClient'
import { AppErrorBoundary } from './components/AppErrorBoundary'
import { contentFromApi, registerContentAuth } from './data/contentSource'
import { loadBank, type Question } from './data/questions'
import { initSentry } from './lib/sentry'
import './index.css'
// KaTeX CSS — ships once globally so any <InlineMath> in the tree
// can render without per-component-style imports.
import 'katex/dist/katex.min.css'
import { routeTree } from './routeTree.gen'

// Initialise error capture before anything else so boot-time failures are
// caught. No-op unless VITE_SENTRY_DSN is set (inert by default).
initSentry()

// Expose the resolved bank on `window.__HPC_BANK__` so the Playwright
// e2e suite can resolve the correct answer for the rendered prompt
// without hard-coding it.
function exposeBank(bank: readonly Question[]) {
  ;(window as unknown as { __HPC_BANK__: readonly Question[] }).__HPC_BANK__ = bank
}

// Boot pre-warm of the question bank.
//
// LOCAL mode (dev / e2e / vitest — VITE_CONTENT_FROM_API unset): the
// dataset is a public static asset, so kick the fetch off immediately at
// module scope, in parallel with React mounting + Clerk handshaking. By
// the time the user clicks "Starta övning" the bank is already in
// memory. This is the historical behavior, unchanged.
//
// API mode (staging / production): the dataset is auth-gated behind
// /api/content, so a fetch here — before Clerk is ready — would 401.
// Pre-warm is deferred to <ContentAuthBridge> below, which fires it only
// once Clerk reports a signed-in session and a token getter is
// registered. loadBank() is idempotent, so any picker that calls it
// later still shares the same Promise.
if (!contentFromApi) {
  loadBank().then(exposeBank)
}

// Bridges Clerk's session into the content layer. Renders null. In API
// mode it (a) registers the token getter contentFetch awaits, and (b)
// pre-warms the bank once auth is ready. In local mode it's a harmless
// no-op — the getter is registered but never awaited, and the bank was
// already pre-warmed at module scope.
function ContentAuthBridge() {
  const { getToken, isLoaded, isSignedIn } = useAuth()
  useEffect(() => {
    registerContentAuth(() => getToken())
  }, [getToken])
  useEffect(() => {
    if (contentFromApi && isLoaded && isSignedIn) {
      loadBank().then(exposeBank)
    }
  }, [isLoaded, isSignedIn])
  return null
}

// `routeTree.gen.ts` is auto-generated by @tanstack/router-plugin from the
// files in src/routes. Don't edit it; the plugin rewrites it on every dev
// run and on `pnpm build`.
const router = createRouter({
  routeTree,
  // Default search-param parser; safe in case any route uses `?dev=1`.
  defaultPreload: 'intent',
})

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

// SW update discovery for long-lived tabs. `registerType: 'autoUpdate'`
// only helps once the browser RE-CHECKS sw.js — which happens on hard
// navigations, not SPA route changes. A tab left open across deploys
// (the owner's daily reality, three stale-verification incidents on
// 2026-07-11) never discovers the new version. Poll the registration
// every 60s; when an update lands, autoUpdate's skipWaiting +
// controllerchange reload takes over as before.
registerSW({
  onRegisteredSW(_url, registration) {
    if (!registration) return
    setInterval(() => {
      registration.update().catch(() => {
        // offline / transient — next tick retries.
      })
    }, 60_000)
  },
})

const PUBLISHABLE_KEY = import.meta.env.VITE_CLERK_PUBLISHABLE_KEY as string | undefined
if (!PUBLISHABLE_KEY) {
  throw new Error(
    'Missing VITE_CLERK_PUBLISHABLE_KEY — copy app/.env.example to .env.local and set it',
  )
}

// @clerk/localizations' svSE ships two untranslated strings on the
// sign-in "use email instead" links (the rest of the ~1400 keys are
// fully translated; the remaining English leftovers we found — SAML,
// organizations, web3 wallet — are all features this product doesn't
// use, so they're unreachable and left as-is).
const localization: typeof svSE = {
  ...svSE,
  signIn: {
    ...svSE.signIn,
    start: {
      ...svSE.signIn?.start,
      actionLink__use_email: 'Använd e-post istället',
      actionLink__use_email_username: 'Använd e-post eller användarnamn',
    },
  },
}

const rootEl = document.getElementById('root')
if (!rootEl) throw new Error('Missing #root element in index.html')

createRoot(rootEl).render(
  <StrictMode>
    <AppErrorBoundary>
      <ClerkProvider
        publishableKey={PUBLISHABLE_KEY}
        localization={localization}
        // Map Clerk's redirects to TanStack Router routes so all auth
        // navigations stay inside our SPA shell.
        signInUrl="/sign-in"
        signUpUrl="/sign-up"
        signInFallbackRedirectUrl="/"
        signUpFallbackRedirectUrl="/"
      >
        <QueryClientProvider client={queryClient}>
          <ContentAuthBridge />
          {/* A2 "Arket" motion root: reducedMotion="user" makes every
           *  framer-motion consumer below honour prefers-reduced-motion
           *  without its own guard — springs collapse, ink swaps instantly.
           *  useArketMotion() reads the same signal for imperative animate()
           *  loops (the drill camera, a strip seating home). */}
          <MotionConfig reducedMotion="user">
            <RouterProvider router={router} />
          </MotionConfig>
        </QueryClientProvider>
      </ClerkProvider>
    </AppErrorBoundary>
  </StrictMode>,
)
