/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RepetitionRouteImport } from './routes/repetition'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as DevRouteImport } from './routes/dev'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AvanceratRouteImport } from './routes/avancerat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevExplanationBakeOffRouteImport } from './routes/dev.explanation-bake-off'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RepetitionRoute = RepetitionRouteImport.update({
  id: '/repetition',
  path: '/repetition',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AvanceratRoute = AvanceratRouteImport.update({
  id: '/avancerat',
  path: '/avancerat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevExplanationBakeOffRoute = DevExplanationBakeOffRouteImport.update({
  id: '/explanation-bake-off',
  path: '/explanation-bake-off',
  getParentRoute: () => DevRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avancerat': typeof AvanceratRoute
  '/coach': typeof CoachRoute
  '/dev': typeof DevRouteWithChildren
  '/drill': typeof DrillRoute
  '/progress': typeof ProgressRoute
  '/repetition': typeof RepetitionRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dev/explanation-bake-off': typeof DevExplanationBakeOffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avancerat': typeof AvanceratRoute
  '/coach': typeof CoachRoute
  '/dev': typeof DevRouteWithChildren
  '/drill': typeof DrillRoute
  '/progress': typeof ProgressRoute
  '/repetition': typeof RepetitionRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dev/explanation-bake-off': typeof DevExplanationBakeOffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avancerat': typeof AvanceratRoute
  '/coach': typeof CoachRoute
  '/dev': typeof DevRouteWithChildren
  '/drill': typeof DrillRoute
  '/progress': typeof ProgressRoute
  '/repetition': typeof RepetitionRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dev/explanation-bake-off': typeof DevExplanationBakeOffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avancerat'
    | '/coach'
    | '/dev'
    | '/drill'
    | '/progress'
    | '/repetition'
    | '/sign-in'
    | '/sign-up'
    | '/dev/explanation-bake-off'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avancerat'
    | '/coach'
    | '/dev'
    | '/drill'
    | '/progress'
    | '/repetition'
    | '/sign-in'
    | '/sign-up'
    | '/dev/explanation-bake-off'
  id:
    | '__root__'
    | '/'
    | '/avancerat'
    | '/coach'
    | '/dev'
    | '/drill'
    | '/progress'
    | '/repetition'
    | '/sign-in'
    | '/sign-up'
    | '/dev/explanation-bake-off'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvanceratRoute: typeof AvanceratRoute
  CoachRoute: typeof CoachRoute
  DevRoute: typeof DevRouteWithChildren
  DrillRoute: typeof DrillRoute
  ProgressRoute: typeof ProgressRoute
  RepetitionRoute: typeof RepetitionRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repetition': {
      id: '/repetition'
      path: '/repetition'
      fullPath: '/repetition'
      preLoaderRoute: typeof RepetitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avancerat': {
      id: '/avancerat'
      path: '/avancerat'
      fullPath: '/avancerat'
      preLoaderRoute: typeof AvanceratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/explanation-bake-off': {
      id: '/dev/explanation-bake-off'
      path: '/explanation-bake-off'
      fullPath: '/dev/explanation-bake-off'
      preLoaderRoute: typeof DevExplanationBakeOffRouteImport
      parentRoute: typeof DevRoute
    }
  }
}

interface DevRouteChildren {
  DevExplanationBakeOffRoute: typeof DevExplanationBakeOffRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevExplanationBakeOffRoute: DevExplanationBakeOffRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvanceratRoute: AvanceratRoute,
  CoachRoute: CoachRoute,
  DevRoute: DevRouteWithChildren,
  DrillRoute: DrillRoute,
  ProgressRoute: ProgressRoute,
  RepetitionRoute: RepetitionRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
