/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInBakeoffRouteImport } from './routes/sign-in-bakeoff'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RepetitionRouteImport } from './routes/repetition'
import { Route as RedesignLayoutBakeoffRouteImport } from './routes/redesign-layout-bakeoff'
import { Route as RedesignLabRouteImport } from './routes/redesign-lab'
import { Route as RedesignL12RouteImport } from './routes/redesign-l12'
import { Route as RedesignBakeoffRouteImport } from './routes/redesign-bakeoff'
import { Route as ProvVerifyRouteImport } from './routes/prov-verify'
import { Route as ProvRouteImport } from './routes/prov'
import { Route as ProgressBakeoffRouteImport } from './routes/progress-bakeoff'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as NavBakeoffRouteImport } from './routes/nav-bakeoff'
import { Route as MerRouteImport } from './routes/mer'
import { Route as MCompareRouteImport } from './routes/m-compare'
import { Route as LoopBakeoffRouteImport } from './routes/loop-bakeoff'
import { Route as LektionPracticeBakeoffRouteImport } from './routes/lektion-practice-bakeoff'
import { Route as LektionRouteImport } from './routes/lektion'
import { Route as KlartBakeoffRouteImport } from './routes/klart-bakeoff'
import { Route as HomePhoneResumeBakeoffRouteImport } from './routes/home-phone-resume-bakeoff'
import { Route as HomeBakeoffRouteImport } from './routes/home-bakeoff'
import { Route as HistorikPlacementBakeoffRouteImport } from './routes/historik-placement-bakeoff'
import { Route as HistorikRouteImport } from './routes/historik'
import { Route as ExplanationBakeOffRouteImport } from './routes/explanation-bake-off'
import { Route as DtkBrowserRouteImport } from './routes/dtk-browser'
import { Route as DtkBlockBakeoffRouteImport } from './routes/dtk-block-bakeoff'
import { Route as DrillStyleCRouteImport } from './routes/drill-style-c'
import { Route as DrillStyleBRouteImport } from './routes/drill-style-b'
import { Route as DrillStyleARouteImport } from './routes/drill-style-a'
import { Route as DrillBakeOffRouteImport } from './routes/drill-bake-off'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as DiagnostikRouteImport } from './routes/diagnostik'
import { Route as DevLoginRouteImport } from './routes/dev-login'
import { Route as DevRouteImport } from './routes/dev'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AvanceratRouteImport } from './routes/avancerat'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInBakeoffRoute = SignInBakeoffRouteImport.update({
  id: '/sign-in-bakeoff',
  path: '/sign-in-bakeoff',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RepetitionRoute = RepetitionRouteImport.update({
  id: '/repetition',
  path: '/repetition',
  getParentRoute: () => rootRouteImport,
} as any)
const RedesignLayoutBakeoffRoute = RedesignLayoutBakeoffRouteImport.update({
  id: '/redesign-layout-bakeoff',
  path: '/redesign-layout-bakeoff',
  getParentRoute: () => rootRouteImport,
} as any)
const RedesignLabRoute = RedesignLabRouteImport.update({
  id: '/redesign-lab',
  path: '/redesign-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const RedesignL12Route = RedesignL12RouteImport.update({
  id: '/redesign-l12',
  path: '/redesign-l12',
  getParentRoute: () => rootRouteImport,
} as any)
const RedesignBakeoffRoute = RedesignBakeoffRouteImport.update({
  id: '/redesign-bakeoff',
  path: '/redesign-bakeoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvVerifyRoute = ProvVerifyRouteImport.update({
  id: '/prov-verify',
  path: '/prov-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvRoute = ProvRouteImport.update({
  id: '/prov',
  path: '/prov',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressBakeoffRoute = ProgressBakeoffRouteImport.update({
  id: '/progress-bakeoff',
  path: '/progress-bakeoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const NavBakeoffRoute = NavBakeoffRouteImport.update({
  id: '/nav-bakeoff',
  path: '/nav-bakeoff',
  getParentRoute: () => rootRouteImport,
} as any)
const MerRoute = MerRouteImport.update({
  id: '/mer',
  path: '/mer',
  getParentRoute: () => rootRouteImport,
} as any)
const MCompareRoute = MCompareRouteImport.update({
  id: '/m-compare',
  path: '/m-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopBakeoffRoute = LoopBakeoffRouteImport.update({
  id: '/loop-bakeoff',
  path: '/loop-bakeoff',
  getParentRoute: () => rootRouteImport,
} as any)
const LektionPracticeBakeoffRoute = LektionPracticeBakeoffRouteImport.update({
  id: '/lektion-practice-bakeoff',
  path: '/lektion-practice-bakeoff',
  getParentRoute: () => rootRouteImport,
} as any)
const LektionRoute = LektionRouteImport.update({
  id: '/lektion',
  path: '/lektion',
  getParentRoute: () => rootRouteImport,
} as any)
const KlartBakeoffRoute = KlartBakeoffRouteImport.update({
  id: '/klart-bakeoff',
  path: '/klart-bakeoff',
  getParentRoute: () => rootRouteImport,
} as any)
const HomePhoneResumeBakeoffRoute = HomePhoneResumeBakeoffRouteImport.update({
  id: '/home-phone-resume-bakeoff',
  path: '/home-phone-resume-bakeoff',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeBakeoffRoute = HomeBakeoffRouteImport.update({
  id: '/home-bakeoff',
  path: '/home-bakeoff',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorikPlacementBakeoffRoute =
  HistorikPlacementBakeoffRouteImport.update({
    id: '/historik-placement-bakeoff',
    path: '/historik-placement-bakeoff',
    getParentRoute: () => rootRouteImport,
  } as any)
const HistorikRoute = HistorikRouteImport.update({
  id: '/historik',
  path: '/historik',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplanationBakeOffRoute = ExplanationBakeOffRouteImport.update({
  id: '/explanation-bake-off',
  path: '/explanation-bake-off',
  getParentRoute: () => rootRouteImport,
} as any)
const DtkBrowserRoute = DtkBrowserRouteImport.update({
  id: '/dtk-browser',
  path: '/dtk-browser',
  getParentRoute: () => rootRouteImport,
} as any)
const DtkBlockBakeoffRoute = DtkBlockBakeoffRouteImport.update({
  id: '/dtk-block-bakeoff',
  path: '/dtk-block-bakeoff',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillStyleCRoute = DrillStyleCRouteImport.update({
  id: '/drill-style-c',
  path: '/drill-style-c',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillStyleBRoute = DrillStyleBRouteImport.update({
  id: '/drill-style-b',
  path: '/drill-style-b',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillStyleARoute = DrillStyleARouteImport.update({
  id: '/drill-style-a',
  path: '/drill-style-a',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillBakeOffRoute = DrillBakeOffRouteImport.update({
  id: '/drill-bake-off',
  path: '/drill-bake-off',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnostikRoute = DiagnostikRouteImport.update({
  id: '/diagnostik',
  path: '/diagnostik',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginRoute = DevLoginRouteImport.update({
  id: '/dev-login',
  path: '/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AvanceratRoute = AvanceratRouteImport.update({
  id: '/avancerat',
  path: '/avancerat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avancerat': typeof AvanceratRoute
  '/coach': typeof CoachRoute
  '/dev': typeof DevRoute
  '/dev-login': typeof DevLoginRoute
  '/diagnostik': typeof DiagnostikRoute
  '/drill': typeof DrillRoute
  '/drill-bake-off': typeof DrillBakeOffRoute
  '/drill-style-a': typeof DrillStyleARoute
  '/drill-style-b': typeof DrillStyleBRoute
  '/drill-style-c': typeof DrillStyleCRoute
  '/dtk-block-bakeoff': typeof DtkBlockBakeoffRoute
  '/dtk-browser': typeof DtkBrowserRoute
  '/explanation-bake-off': typeof ExplanationBakeOffRoute
  '/historik': typeof HistorikRoute
  '/historik-placement-bakeoff': typeof HistorikPlacementBakeoffRoute
  '/home-bakeoff': typeof HomeBakeoffRoute
  '/home-phone-resume-bakeoff': typeof HomePhoneResumeBakeoffRoute
  '/klart-bakeoff': typeof KlartBakeoffRoute
  '/lektion': typeof LektionRoute
  '/lektion-practice-bakeoff': typeof LektionPracticeBakeoffRoute
  '/loop-bakeoff': typeof LoopBakeoffRoute
  '/m-compare': typeof MCompareRoute
  '/mer': typeof MerRoute
  '/nav-bakeoff': typeof NavBakeoffRoute
  '/progress': typeof ProgressRoute
  '/progress-bakeoff': typeof ProgressBakeoffRoute
  '/prov': typeof ProvRoute
  '/prov-verify': typeof ProvVerifyRoute
  '/redesign-bakeoff': typeof RedesignBakeoffRoute
  '/redesign-l12': typeof RedesignL12Route
  '/redesign-lab': typeof RedesignLabRoute
  '/redesign-layout-bakeoff': typeof RedesignLayoutBakeoffRoute
  '/repetition': typeof RepetitionRoute
  '/sign-in': typeof SignInRoute
  '/sign-in-bakeoff': typeof SignInBakeoffRoute
  '/sign-up': typeof SignUpRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avancerat': typeof AvanceratRoute
  '/coach': typeof CoachRoute
  '/dev': typeof DevRoute
  '/dev-login': typeof DevLoginRoute
  '/diagnostik': typeof DiagnostikRoute
  '/drill': typeof DrillRoute
  '/drill-bake-off': typeof DrillBakeOffRoute
  '/drill-style-a': typeof DrillStyleARoute
  '/drill-style-b': typeof DrillStyleBRoute
  '/drill-style-c': typeof DrillStyleCRoute
  '/dtk-block-bakeoff': typeof DtkBlockBakeoffRoute
  '/dtk-browser': typeof DtkBrowserRoute
  '/explanation-bake-off': typeof ExplanationBakeOffRoute
  '/historik': typeof HistorikRoute
  '/historik-placement-bakeoff': typeof HistorikPlacementBakeoffRoute
  '/home-bakeoff': typeof HomeBakeoffRoute
  '/home-phone-resume-bakeoff': typeof HomePhoneResumeBakeoffRoute
  '/klart-bakeoff': typeof KlartBakeoffRoute
  '/lektion': typeof LektionRoute
  '/lektion-practice-bakeoff': typeof LektionPracticeBakeoffRoute
  '/loop-bakeoff': typeof LoopBakeoffRoute
  '/m-compare': typeof MCompareRoute
  '/mer': typeof MerRoute
  '/nav-bakeoff': typeof NavBakeoffRoute
  '/progress': typeof ProgressRoute
  '/progress-bakeoff': typeof ProgressBakeoffRoute
  '/prov': typeof ProvRoute
  '/prov-verify': typeof ProvVerifyRoute
  '/redesign-bakeoff': typeof RedesignBakeoffRoute
  '/redesign-l12': typeof RedesignL12Route
  '/redesign-lab': typeof RedesignLabRoute
  '/redesign-layout-bakeoff': typeof RedesignLayoutBakeoffRoute
  '/repetition': typeof RepetitionRoute
  '/sign-in': typeof SignInRoute
  '/sign-in-bakeoff': typeof SignInBakeoffRoute
  '/sign-up': typeof SignUpRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avancerat': typeof AvanceratRoute
  '/coach': typeof CoachRoute
  '/dev': typeof DevRoute
  '/dev-login': typeof DevLoginRoute
  '/diagnostik': typeof DiagnostikRoute
  '/drill': typeof DrillRoute
  '/drill-bake-off': typeof DrillBakeOffRoute
  '/drill-style-a': typeof DrillStyleARoute
  '/drill-style-b': typeof DrillStyleBRoute
  '/drill-style-c': typeof DrillStyleCRoute
  '/dtk-block-bakeoff': typeof DtkBlockBakeoffRoute
  '/dtk-browser': typeof DtkBrowserRoute
  '/explanation-bake-off': typeof ExplanationBakeOffRoute
  '/historik': typeof HistorikRoute
  '/historik-placement-bakeoff': typeof HistorikPlacementBakeoffRoute
  '/home-bakeoff': typeof HomeBakeoffRoute
  '/home-phone-resume-bakeoff': typeof HomePhoneResumeBakeoffRoute
  '/klart-bakeoff': typeof KlartBakeoffRoute
  '/lektion': typeof LektionRoute
  '/lektion-practice-bakeoff': typeof LektionPracticeBakeoffRoute
  '/loop-bakeoff': typeof LoopBakeoffRoute
  '/m-compare': typeof MCompareRoute
  '/mer': typeof MerRoute
  '/nav-bakeoff': typeof NavBakeoffRoute
  '/progress': typeof ProgressRoute
  '/progress-bakeoff': typeof ProgressBakeoffRoute
  '/prov': typeof ProvRoute
  '/prov-verify': typeof ProvVerifyRoute
  '/redesign-bakeoff': typeof RedesignBakeoffRoute
  '/redesign-l12': typeof RedesignL12Route
  '/redesign-lab': typeof RedesignLabRoute
  '/redesign-layout-bakeoff': typeof RedesignLayoutBakeoffRoute
  '/repetition': typeof RepetitionRoute
  '/sign-in': typeof SignInRoute
  '/sign-in-bakeoff': typeof SignInBakeoffRoute
  '/sign-up': typeof SignUpRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avancerat'
    | '/coach'
    | '/dev'
    | '/dev-login'
    | '/diagnostik'
    | '/drill'
    | '/drill-bake-off'
    | '/drill-style-a'
    | '/drill-style-b'
    | '/drill-style-c'
    | '/dtk-block-bakeoff'
    | '/dtk-browser'
    | '/explanation-bake-off'
    | '/historik'
    | '/historik-placement-bakeoff'
    | '/home-bakeoff'
    | '/home-phone-resume-bakeoff'
    | '/klart-bakeoff'
    | '/lektion'
    | '/lektion-practice-bakeoff'
    | '/loop-bakeoff'
    | '/m-compare'
    | '/mer'
    | '/nav-bakeoff'
    | '/progress'
    | '/progress-bakeoff'
    | '/prov'
    | '/prov-verify'
    | '/redesign-bakeoff'
    | '/redesign-l12'
    | '/redesign-lab'
    | '/redesign-layout-bakeoff'
    | '/repetition'
    | '/sign-in'
    | '/sign-in-bakeoff'
    | '/sign-up'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avancerat'
    | '/coach'
    | '/dev'
    | '/dev-login'
    | '/diagnostik'
    | '/drill'
    | '/drill-bake-off'
    | '/drill-style-a'
    | '/drill-style-b'
    | '/drill-style-c'
    | '/dtk-block-bakeoff'
    | '/dtk-browser'
    | '/explanation-bake-off'
    | '/historik'
    | '/historik-placement-bakeoff'
    | '/home-bakeoff'
    | '/home-phone-resume-bakeoff'
    | '/klart-bakeoff'
    | '/lektion'
    | '/lektion-practice-bakeoff'
    | '/loop-bakeoff'
    | '/m-compare'
    | '/mer'
    | '/nav-bakeoff'
    | '/progress'
    | '/progress-bakeoff'
    | '/prov'
    | '/prov-verify'
    | '/redesign-bakeoff'
    | '/redesign-l12'
    | '/redesign-lab'
    | '/redesign-layout-bakeoff'
    | '/repetition'
    | '/sign-in'
    | '/sign-in-bakeoff'
    | '/sign-up'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/avancerat'
    | '/coach'
    | '/dev'
    | '/dev-login'
    | '/diagnostik'
    | '/drill'
    | '/drill-bake-off'
    | '/drill-style-a'
    | '/drill-style-b'
    | '/drill-style-c'
    | '/dtk-block-bakeoff'
    | '/dtk-browser'
    | '/explanation-bake-off'
    | '/historik'
    | '/historik-placement-bakeoff'
    | '/home-bakeoff'
    | '/home-phone-resume-bakeoff'
    | '/klart-bakeoff'
    | '/lektion'
    | '/lektion-practice-bakeoff'
    | '/loop-bakeoff'
    | '/m-compare'
    | '/mer'
    | '/nav-bakeoff'
    | '/progress'
    | '/progress-bakeoff'
    | '/prov'
    | '/prov-verify'
    | '/redesign-bakeoff'
    | '/redesign-l12'
    | '/redesign-lab'
    | '/redesign-layout-bakeoff'
    | '/repetition'
    | '/sign-in'
    | '/sign-in-bakeoff'
    | '/sign-up'
    | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvanceratRoute: typeof AvanceratRoute
  CoachRoute: typeof CoachRoute
  DevRoute: typeof DevRoute
  DevLoginRoute: typeof DevLoginRoute
  DiagnostikRoute: typeof DiagnostikRoute
  DrillRoute: typeof DrillRoute
  DrillBakeOffRoute: typeof DrillBakeOffRoute
  DrillStyleARoute: typeof DrillStyleARoute
  DrillStyleBRoute: typeof DrillStyleBRoute
  DrillStyleCRoute: typeof DrillStyleCRoute
  DtkBlockBakeoffRoute: typeof DtkBlockBakeoffRoute
  DtkBrowserRoute: typeof DtkBrowserRoute
  ExplanationBakeOffRoute: typeof ExplanationBakeOffRoute
  HistorikRoute: typeof HistorikRoute
  HistorikPlacementBakeoffRoute: typeof HistorikPlacementBakeoffRoute
  HomeBakeoffRoute: typeof HomeBakeoffRoute
  HomePhoneResumeBakeoffRoute: typeof HomePhoneResumeBakeoffRoute
  KlartBakeoffRoute: typeof KlartBakeoffRoute
  LektionRoute: typeof LektionRoute
  LektionPracticeBakeoffRoute: typeof LektionPracticeBakeoffRoute
  LoopBakeoffRoute: typeof LoopBakeoffRoute
  MCompareRoute: typeof MCompareRoute
  MerRoute: typeof MerRoute
  NavBakeoffRoute: typeof NavBakeoffRoute
  ProgressRoute: typeof ProgressRoute
  ProgressBakeoffRoute: typeof ProgressBakeoffRoute
  ProvRoute: typeof ProvRoute
  ProvVerifyRoute: typeof ProvVerifyRoute
  RedesignBakeoffRoute: typeof RedesignBakeoffRoute
  RedesignL12Route: typeof RedesignL12Route
  RedesignLabRoute: typeof RedesignLabRoute
  RedesignLayoutBakeoffRoute: typeof RedesignLayoutBakeoffRoute
  RepetitionRoute: typeof RepetitionRoute
  SignInRoute: typeof SignInRoute
  SignInBakeoffRoute: typeof SignInBakeoffRoute
  SignUpRoute: typeof SignUpRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in-bakeoff': {
      id: '/sign-in-bakeoff'
      path: '/sign-in-bakeoff'
      fullPath: '/sign-in-bakeoff'
      preLoaderRoute: typeof SignInBakeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repetition': {
      id: '/repetition'
      path: '/repetition'
      fullPath: '/repetition'
      preLoaderRoute: typeof RepetitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redesign-layout-bakeoff': {
      id: '/redesign-layout-bakeoff'
      path: '/redesign-layout-bakeoff'
      fullPath: '/redesign-layout-bakeoff'
      preLoaderRoute: typeof RedesignLayoutBakeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redesign-lab': {
      id: '/redesign-lab'
      path: '/redesign-lab'
      fullPath: '/redesign-lab'
      preLoaderRoute: typeof RedesignLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redesign-l12': {
      id: '/redesign-l12'
      path: '/redesign-l12'
      fullPath: '/redesign-l12'
      preLoaderRoute: typeof RedesignL12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redesign-bakeoff': {
      id: '/redesign-bakeoff'
      path: '/redesign-bakeoff'
      fullPath: '/redesign-bakeoff'
      preLoaderRoute: typeof RedesignBakeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prov-verify': {
      id: '/prov-verify'
      path: '/prov-verify'
      fullPath: '/prov-verify'
      preLoaderRoute: typeof ProvVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prov': {
      id: '/prov'
      path: '/prov'
      fullPath: '/prov'
      preLoaderRoute: typeof ProvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress-bakeoff': {
      id: '/progress-bakeoff'
      path: '/progress-bakeoff'
      fullPath: '/progress-bakeoff'
      preLoaderRoute: typeof ProgressBakeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nav-bakeoff': {
      id: '/nav-bakeoff'
      path: '/nav-bakeoff'
      fullPath: '/nav-bakeoff'
      preLoaderRoute: typeof NavBakeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mer': {
      id: '/mer'
      path: '/mer'
      fullPath: '/mer'
      preLoaderRoute: typeof MerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m-compare': {
      id: '/m-compare'
      path: '/m-compare'
      fullPath: '/m-compare'
      preLoaderRoute: typeof MCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loop-bakeoff': {
      id: '/loop-bakeoff'
      path: '/loop-bakeoff'
      fullPath: '/loop-bakeoff'
      preLoaderRoute: typeof LoopBakeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lektion-practice-bakeoff': {
      id: '/lektion-practice-bakeoff'
      path: '/lektion-practice-bakeoff'
      fullPath: '/lektion-practice-bakeoff'
      preLoaderRoute: typeof LektionPracticeBakeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lektion': {
      id: '/lektion'
      path: '/lektion'
      fullPath: '/lektion'
      preLoaderRoute: typeof LektionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klart-bakeoff': {
      id: '/klart-bakeoff'
      path: '/klart-bakeoff'
      fullPath: '/klart-bakeoff'
      preLoaderRoute: typeof KlartBakeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-phone-resume-bakeoff': {
      id: '/home-phone-resume-bakeoff'
      path: '/home-phone-resume-bakeoff'
      fullPath: '/home-phone-resume-bakeoff'
      preLoaderRoute: typeof HomePhoneResumeBakeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-bakeoff': {
      id: '/home-bakeoff'
      path: '/home-bakeoff'
      fullPath: '/home-bakeoff'
      preLoaderRoute: typeof HomeBakeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historik-placement-bakeoff': {
      id: '/historik-placement-bakeoff'
      path: '/historik-placement-bakeoff'
      fullPath: '/historik-placement-bakeoff'
      preLoaderRoute: typeof HistorikPlacementBakeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historik': {
      id: '/historik'
      path: '/historik'
      fullPath: '/historik'
      preLoaderRoute: typeof HistorikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explanation-bake-off': {
      id: '/explanation-bake-off'
      path: '/explanation-bake-off'
      fullPath: '/explanation-bake-off'
      preLoaderRoute: typeof ExplanationBakeOffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dtk-browser': {
      id: '/dtk-browser'
      path: '/dtk-browser'
      fullPath: '/dtk-browser'
      preLoaderRoute: typeof DtkBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dtk-block-bakeoff': {
      id: '/dtk-block-bakeoff'
      path: '/dtk-block-bakeoff'
      fullPath: '/dtk-block-bakeoff'
      preLoaderRoute: typeof DtkBlockBakeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill-style-c': {
      id: '/drill-style-c'
      path: '/drill-style-c'
      fullPath: '/drill-style-c'
      preLoaderRoute: typeof DrillStyleCRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill-style-b': {
      id: '/drill-style-b'
      path: '/drill-style-b'
      fullPath: '/drill-style-b'
      preLoaderRoute: typeof DrillStyleBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill-style-a': {
      id: '/drill-style-a'
      path: '/drill-style-a'
      fullPath: '/drill-style-a'
      preLoaderRoute: typeof DrillStyleARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill-bake-off': {
      id: '/drill-bake-off'
      path: '/drill-bake-off'
      fullPath: '/drill-bake-off'
      preLoaderRoute: typeof DrillBakeOffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostik': {
      id: '/diagnostik'
      path: '/diagnostik'
      fullPath: '/diagnostik'
      preLoaderRoute: typeof DiagnostikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-login': {
      id: '/dev-login'
      path: '/dev-login'
      fullPath: '/dev-login'
      preLoaderRoute: typeof DevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avancerat': {
      id: '/avancerat'
      path: '/avancerat'
      fullPath: '/avancerat'
      preLoaderRoute: typeof AvanceratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvanceratRoute: AvanceratRoute,
  CoachRoute: CoachRoute,
  DevRoute: DevRoute,
  DevLoginRoute: DevLoginRoute,
  DiagnostikRoute: DiagnostikRoute,
  DrillRoute: DrillRoute,
  DrillBakeOffRoute: DrillBakeOffRoute,
  DrillStyleARoute: DrillStyleARoute,
  DrillStyleBRoute: DrillStyleBRoute,
  DrillStyleCRoute: DrillStyleCRoute,
  DtkBlockBakeoffRoute: DtkBlockBakeoffRoute,
  DtkBrowserRoute: DtkBrowserRoute,
  ExplanationBakeOffRoute: ExplanationBakeOffRoute,
  HistorikRoute: HistorikRoute,
  HistorikPlacementBakeoffRoute: HistorikPlacementBakeoffRoute,
  HomeBakeoffRoute: HomeBakeoffRoute,
  HomePhoneResumeBakeoffRoute: HomePhoneResumeBakeoffRoute,
  KlartBakeoffRoute: KlartBakeoffRoute,
  LektionRoute: LektionRoute,
  LektionPracticeBakeoffRoute: LektionPracticeBakeoffRoute,
  LoopBakeoffRoute: LoopBakeoffRoute,
  MCompareRoute: MCompareRoute,
  MerRoute: MerRoute,
  NavBakeoffRoute: NavBakeoffRoute,
  ProgressRoute: ProgressRoute,
  ProgressBakeoffRoute: ProgressBakeoffRoute,
  ProvRoute: ProvRoute,
  ProvVerifyRoute: ProvVerifyRoute,
  RedesignBakeoffRoute: RedesignBakeoffRoute,
  RedesignL12Route: RedesignL12Route,
  RedesignLabRoute: RedesignLabRoute,
  RedesignLayoutBakeoffRoute: RedesignLayoutBakeoffRoute,
  RepetitionRoute: RepetitionRoute,
  SignInRoute: SignInRoute,
  SignInBakeoffRoute: SignInBakeoffRoute,
  SignUpRoute: SignUpRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
