/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as DevRouteImport } from './routes/dev'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AvanceratRouteImport } from './routes/avancerat'
import { Route as IndexRouteImport } from './routes/index'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AvanceratRoute = AvanceratRouteImport.update({
  id: '/avancerat',
  path: '/avancerat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avancerat': typeof AvanceratRoute
  '/coach': typeof CoachRoute
  '/dev': typeof DevRoute
  '/drill': typeof DrillRoute
  '/progress': typeof ProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avancerat': typeof AvanceratRoute
  '/coach': typeof CoachRoute
  '/dev': typeof DevRoute
  '/drill': typeof DrillRoute
  '/progress': typeof ProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avancerat': typeof AvanceratRoute
  '/coach': typeof CoachRoute
  '/dev': typeof DevRoute
  '/drill': typeof DrillRoute
  '/progress': typeof ProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/avancerat' | '/coach' | '/dev' | '/drill' | '/progress'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/avancerat' | '/coach' | '/dev' | '/drill' | '/progress'
  id:
    | '__root__'
    | '/'
    | '/avancerat'
    | '/coach'
    | '/dev'
    | '/drill'
    | '/progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvanceratRoute: typeof AvanceratRoute
  CoachRoute: typeof CoachRoute
  DevRoute: typeof DevRoute
  DrillRoute: typeof DrillRoute
  ProgressRoute: typeof ProgressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avancerat': {
      id: '/avancerat'
      path: '/avancerat'
      fullPath: '/avancerat'
      preLoaderRoute: typeof AvanceratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvanceratRoute: AvanceratRoute,
  CoachRoute: CoachRoute,
  DevRoute: DevRoute,
  DrillRoute: DrillRoute,
  ProgressRoute: ProgressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
