"""Variant-C Ultra-Granular ELF regeneration for var-2015.

20 entries: 10 comprehension (verb1) + 10 mixed (verb2: 5 cloze + 5 comp).
NO API — hand-authored to match the locked Variant C recipe.
Saves checkpoints every 5 to audit/_regen/var-2015-elf.json.
"""
from __future__ import annotations

import json
from pathlib import Path

META = {
    "model": "claude-opus-4-7",
    "generated_at": "2026-05-14",
    "recipe": "variant-c-ultra-granular",
}

OUT = Path("audit/_regen/var-2015-elf.json")

ENTRIES: dict[str, dict] = {}


def add(qid: str, payload: dict) -> None:
    payload["_meta"] = META
    payload.setdefault("framework_id", None)
    ENTRIES[qid] = payload


# ════════════════════════════════════════════════════════════════════
# verb1 — Reading comprehension passages
# Passage 1: "Butterflies" (Q31), "Vacuum" (Q32)
# Passage 2: "The Literate Ape" (Q33–37, long review by Owen Flanagan)
# Passage 3 (shorter): "Election Time" (Q38), "Blogging" (Q39)
# Passage 4: "The 1960s" (Q40)
# ════════════════════════════════════════════════════════════════════

# Q31 — Butterflies, main point — ans C
add("var-2015-verb1-ELF-031", {
    "solution_path": "The 'Butterflies' paragraph says butterflies are 'an excellent indicator species' whose decline 'probably indicates a rapid decline in invertebrates in general'. That makes them a signal for wider ecological change — exactly what C says.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "The prompt is 'What is the main point here?' — so you need the single idea that holds the whole 'Butterflies' paragraph together, not a vivid detail. Main-point questions reward the framing sentence over the imagery.", "tier": "essential"},
        {"n": 2, "title": "Locate the key sentences", "text": "Two sentences carry the argument. The middle one labels them: 'butterflies are an excellent indicator species: if butterflies are suffering, then so too are less well monitored insects…'. The closing one nails it down: 'Butterflies' decline probably indicates a rapid decline in invertebrates in general.'", "tier": "essential"},
        {"n": 3, "title": "Restate in plain English", "text": "Boiled down: butterflies look cute and useless next to eagles or bees, but if they vanish it tells us that many other less-visible insects are vanishing too. They are an early-warning sign for the wider ecosystem.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Indicator species' = a species whose health reflects the health of a wider ecosystem; if it suffers, others probably do too. 'Invertebrates' = animals without a backbone (insects, worms, snails). 'Inconsequential ornaments' = pretty things that don't seem to do anything important.", "tier": "detail"},
        {"n": 5, "title": "Match against the options", "text": "Walk each option against the paraphrase. A says butterflies are 'more vulnerable than most other insects' — the passage never ranks vulnerability; it uses butterflies as a measure of OTHERS. B says Britain has lost most of its butterflies due to pollution — the paragraph mentions extinction every century but never blames pollution specifically. C says butterflies 'help us notice changes in the ecological system' — that is exactly the 'indicator species' idea from step 2. D says preying animals are important for understanding ecology — the paragraph mentions predators only as one of many things butterflies do; it isn't the headline.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is C. The paragraph's whole reason for caring about butterflies is that they signal the health of the wider invertebrate world — that's the main point.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "A", "why_tempting": "It's easy to read 'butterflies have become extinct in Britain' and conclude the paragraph is ranking butterflies as the most fragile insect.", "why_wrong": "The passage uses butterflies as a STAND-IN for less-monitored insects — the claim is about correlated decline, not about who is more fragile. Step 3 shows the trajectory is collective, not comparative."},
        {"letter": "B", "why_tempting": "First instinct on 'extinct in Britain' is to assume a specific cause, and pollution is the textbook answer.", "why_wrong": "The text gives no cause for the extinctions — it only notes that they happen every century. B imports an explanation the passage never offers. Step 2's key sentences talk about consequences, not causes."},
        {"letter": "D", "why_tempting": "Many stop at 'protect other species by preying on pests' and read predators as the focus of the paragraph.", "why_wrong": "Predation is one item in a list of services butterflies indicate (pollination, decomposition, predation). The headline is the indicator role, not predation specifically. Step 5 lines this up — D promotes a list-item into the thesis."},
    ],
    "technique": "On 'main point' items, find the labelling sentence — the one that NAMES the role the subject plays ('indicator species', 'a robust genre', 'an exaptation'). That sentence almost always equals the correct option. Trigger: prompt asks for the main point or headline.",
    "pitfall": "Vivid extinction or imagery details (centuries, eagles, bees) pull your eye to specific facts and tempt you to pick an option that names one of them. The headline sits in the labelling clause ('indicator species'), not in the surrounding examples.",
})

# Q32 — Vacuum, what is said about "vacuum"? — ans B
add("var-2015-verb1-ELF-032", {
    "solution_path": "The 'Vacuum' paragraph says 'In quantum mechanics, the uncertainty principle says we can never be sure that an apparent vacuum is truly empty.' Quantum mechanics raises doubt about the classical idea of vacuum — exactly what B claims.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "The prompt is 'What is said about the concept of “vacuum”?' — so you need a claim the paragraph actually makes about vacuum itself, not about Newton or interstellar dust. Watch for options that hijack a side detail.", "tier": "essential"},
        {"n": 2, "title": "Locate the key sentences", "text": "Three sentences matter. The setup: 'A ball spinning in a vacuum should never slow down… At least that is what Isaac Newton would have said.' The pivot: 'But what if the vacuum itself creates a type of friction…?' The clincher: 'In quantum mechanics, the uncertainty principle says we can never be sure that an apparent vacuum is truly empty.'", "tier": "essential"},
        {"n": 3, "title": "Restate in plain English", "text": "Classical physics treats vacuum as truly empty — nothing inside, no friction, perpetual spin. Quantum mechanics challenges that: thanks to the uncertainty principle, even an 'empty' vacuum is fizzing with photons that pop in and out. So the old idea of vacuum is being questioned.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Vacuum' = a space with no matter in it (in classical physics, perfectly empty). 'Uncertainty principle' = a quantum-mechanics rule saying we can never measure certain pairs of properties at the same time. 'Apparent vacuum' = a space that LOOKS empty but might not be. 'Fizzing with photons' = particles popping in and out at the smallest scale.", "tier": "detail"},
        {"n": 5, "title": "Match against the options", "text": "Walk each option. A claims vacuum is important in producing automated vehicles — the paragraph never mentions vehicles. B says vacuum is questioned in quantum mechanics — matches step 3 directly: uncertainty principle, photons, no truly empty space. C says vacuum is the term for empty space DISCOVERED BY Newton — the text says Newton DESCRIBED what would happen in a vacuum, not that he discovered it. D says vacuum is one of the LEAST RESEARCHED phenomena — the opposite is suggested; vacuum is being actively probed by quantum physics here.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is B. The whole paragraph is built around a contrast: Newton's classical picture of vacuum vs. the quantum-mechanical picture, which questions whether vacuum is really empty.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "A", "why_tempting": "First instinct on 'friction that puts the brakes on spinning objects' is to think of car brakes and automated vehicles — engineering applications.", "why_wrong": "The 'spinning objects' the passage names are interstellar dust grains, not vehicles. A grafts an everyday image onto a cosmological argument. Step 2's locations show the spinning is in space, not a garage."},
        {"letter": "C", "why_tempting": "Newton is famous for big discoveries, so reading 'Isaac Newton would have said' as 'discovered by Newton' feels natural.", "why_wrong": "'Would have said' is a hypothetical attribution — Newton is being used as the spokesman for classical physics, not credited with discovering vacuum. Step 4's vocabulary work separates description from discovery."},
        {"letter": "D", "why_tempting": "It's tempting to read 'might soon be detectable' as 'we barely know anything yet' — i.e. under-researched.", "why_wrong": "The paragraph shows vacuum is the subject of active quantum-mechanical investigation, with detectable predictions on the horizon. Step 3's paraphrase highlights this — D inverts the level of research interest."},
    ],
    "technique": "On 'what is said about X' items, the X almost always sits in the sentence that CHALLENGES or RESHAPES the everyday view of X. Skim for words like 'but', 'however', 'in fact', 'we can never be sure': they flag where the passage stakes its claim.",
    "pitfall": "Famous names in a science paragraph (Newton, Einstein) tempt you to credit them with the topic itself. Read what they actually SAY in the text — usually they are stand-ins for an older view that the passage then complicates.",
})

# Q33 — Literate Ape, implied about reading and the brain — ans D
add("var-2015-verb1-ELF-033", {
    "solution_path": "Owen Flanagan's review notes that reading is only ~5,000 years old while the modern brain is ~200,000 years old, yet the same brain 'letterbox' lights up across all readers. The brain therefore had the capacity to read long before reading existed — exactly what D says.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "The prompt is 'What is IMPLIED about reading in relation to the human brain?' — so you need an inference the passage supports, not a claim it states outright. Watch for options that overreach beyond what's implied.", "tier": "essential"},
        {"n": 2, "title": "Locate the key sentences", "text": "Two sentences carry the implication. 'Evidence suggests that reading… is only about 5000 years old. The brain in its modern form is about 200,000 years old, yet brain imaging shows reading taking place in the same way and in the same place in all brains.' And the framing: the 'letterbox' 'must be an exaptation: a brain area that evolved to do one thing but has been co-opted to do another.'", "tier": "essential"},
        {"n": 3, "title": "Restate in plain English", "text": "Reading is a young invention (5,000 years). The brain is much older (200,000 years) and didn't evolve any new wiring to handle reading. Yet every reader uses the same brain spot to read. So that spot must have already been there, ready to be repurposed — meaning the brain had the latent capacity for reading long before anyone invented it.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Exaptation' = a trait that evolved for one purpose but ended up serving another (here, an area that evolved for visual tracking now handles reading). 'Co-opted' = taken over for a new use. 'Adaptation' = a feature that evolved BECAUSE of the function it now serves. The passage explicitly rules out adaptation for reading and proposes exaptation instead.", "tier": "detail"},
        {"n": 5, "title": "Match against the options", "text": "Walk each option. A says reading affected the structure of the brain in important ways — the opposite of the passage, which argues reading is too recent to have changed brain anatomy. B says the brain shows considerable individual variation in reading — the text says the reading spot is universal to within a few millimetres. C says reading developed due to recent brain anatomy changes — again the opposite; the brain hasn't changed, the brain was already capable. D says the brain had a potential for reading long before reading was invented — matches step 3 exactly.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is D. The whole 'reading paradox' is set up to support exactly this implication: the brain's reading capacity predates reading itself.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "A", "why_tempting": "It's easy to read 'reading taking place in the same place in all brains' as 'reading shaped the brain in a deep way'.", "why_wrong": "The passage uses universality to argue the OPPOSITE — the brain area was there first and reading slotted in. Step 2's exaptation framing rules out the idea that reading shaped the structure."},
        {"letter": "B", "why_tempting": "Many readers expect cognitive abilities to vary a lot person to person, so 'considerable individual variation' sounds plausible.", "why_wrong": "The text explicitly says the letterbox sits 'to within a few millimetres' in every brain — variation is minimal, not considerable. Step 3's paraphrase makes the universality the headline."},
        {"letter": "C", "why_tempting": "If reading is universal across brains, you might assume the brain evolved to support it.", "why_wrong": "The whole 'reading paradox' setup is that reading is too RECENT for any such evolution to have happened. Step 4's vocabulary work — adaptation vs. exaptation — separates these two possibilities."},
    ],
    "technique": "On 'what is implied' items in science prose, the implication usually sits where the author sets up a PARADOX and then resolves it. Find the paradox sentence ('yet brain imaging shows…'), and the correct option will be the resolution the author leans toward.",
    "pitfall": "Reading-and-brain options often look interchangeable on first glance because they all use the same vocabulary (reading, brain, structure, evolution). Pin the DIRECTION the passage moves — brain pre-dates reading, not the other way round — and the wrong options collapse fast.",
})

# Q34 — letterbox area — ans A
add("var-2015-verb1-ELF-034", {
    "solution_path": "The review frames the 'letterbox' as 'an “exaptation”: a brain area that evolved to do one thing but has been co-opted to do another.' Originally designed for something else (visual tracking of animals), then repurposed for reading — exactly what A says.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "The prompt asks specifically about the 'letterbox' area. So you need a claim about its ORIGIN — what it was for before reading came along — not a claim about reading in general.", "tier": "essential"},
        {"n": 2, "title": "Locate the key sentences", "text": "The key formulation: 'it must be an “exaptation”: a brain area that evolved to do one thing but has been co-opted to do another.' And later: 'The area that reading co-opted originally evolved for the visual acuity needed to track animals, a skill with obvious survival benefits.'", "tier": "essential"},
        {"n": 3, "title": "Restate in plain English", "text": "The letterbox wasn't built for reading — reading borrowed it. Originally the area evolved so our ancestors could spot animals (the curves and edges that make up a prey or predator). Now those same circuits recognise letter shapes. Same wiring, different job.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Letterbox' = Dehaene's nickname for the brain spot that handles reading. 'Visual acuity' = sharpness of sight; ability to pick out fine visual detail. 'Survival benefits' = traits that help an organism live long enough to reproduce. The original function — tracking animals — had clear survival value; reading does not.", "tier": "detail"},
        {"n": 5, "title": "Match against the options", "text": "Walk each option. A says the letterbox was originally designed for OTHER purposes — matches the exaptation framing and the visual-tracking origin. B says it was 'from the start closely related to more general communicative functions' — the passage says the opposite, the letterbox does NOT 'ride on top of areas used for speech'. C says it developed early due to basic evolutionary pressure — but the pressure was for visual tracking, and the OPTION says nothing specific; meanwhile A is more precise. D says it is part of the brain area for speech — explicitly contradicted by 'does not ride on top of areas used for speech'.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is A. The letterbox is an exaptation — repurposed from visual tracking — which is just a polished way of saying it was originally designed for other purposes.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "B", "why_tempting": "Reading is a form of communication, so assuming the letterbox started as a general communication area feels natural.", "why_wrong": "The passage explicitly denies this: 'the letterbox does not ride on top of areas used for speech'. Step 2's locations close this off — the letterbox is visual, not communicative in origin."},
        {"letter": "C", "why_tempting": "If the area was there long before reading, 'developed early as a result of basic evolutionary pressure' sounds about right.", "why_wrong": "The pressure was specifically for visual TRACKING of animals — option C is vague enough that it could mean anything. A names the precise relationship (designed for something else); C names a generic mechanism without the content. Step 3's paraphrase pins the original purpose."},
        {"letter": "D", "why_tempting": "Speech and reading both involve language, so a shared brain area is an intuitive guess.", "why_wrong": "Flanagan flags this exact intuition and rules it out: the letterbox is NOT part of the speech area. Step 5 makes this the easiest elimination — the text directly contradicts D."},
    ],
    "technique": "When a passage introduces a technical label ('letterbox', 'exaptation') and then DEFINES it in the next clause, the correct option usually paraphrases that definition. Trigger: prompt names the technical term — look for the colon or dash that defines it.",
    "pitfall": "Speech-and-reading both feel like language, so it is tempting to lump them together neurologically. The passage spends a sentence specifically to rule that out — read for the disavowal, not for what FEELS biologically reasonable.",
})

# Q35 — neuronal recycling hypothesis — ans A
add("var-2015-verb1-ELF-035", {
    "solution_path": "Dehaene's 'neuronal recycling hypothesis' explicitly stakes a middle ground: 'human brain architecture obeys strong genetic constraints, but some circuits have evolved to tolerate a fringe of variability'. Mostly fixed, with room for some modification — exactly what A claims.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "The prompt asks which statement is most in keeping with the 'neuronal recycling hypothesis'. So you need the option that fits the hypothesis as Dehaene FRAMES it, not a general claim about brains.", "tier": "essential"},
        {"n": 2, "title": "Locate the key sentences", "text": "The middle-ground formulation: 'He sees the hypothesis as staking a middle ground between tabula-rasa (the mind as an empty slate) and hard-wired-determinist views (the mind as pre-programmed).' And the direct quote: 'human brain architecture obeys strong genetic constraints, but some circuits have evolved to tolerate a fringe of variability'.", "tier": "essential"},
        {"n": 3, "title": "Restate in plain English", "text": "Two extreme views exist about the brain. One: blank slate, anything can be written on it. Two: hard-wired, completely fixed at birth. Dehaene says reality is in between — most circuits are genetically locked, but a few are flexible enough that they can be repurposed (e.g. by reading). The brain mostly follows fixed rules, with a small zone of plasticity.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Tabula rasa' = Latin for 'blank slate'; the view that the mind starts empty and is shaped entirely by experience. 'Hard-wired-determinist' = the view that the mind is genetically pre-programmed and fixed. 'Fringe of variability' = a small allowance for change; not the whole brain, just the edges. 'Strong genetic constraints' = most of the wiring is locked in by genes.", "tier": "detail"},
        {"n": 5, "title": "Match against the options", "text": "Walk each option. A says the brain mainly functions in a fixed way but there is also room for certain modifications — exactly the middle ground from step 3. B says the tabula-rasa view has little or no relevance to the hypothesis — too strong; Dehaene STAKES A MIDDLE GROUND, which means tabula rasa IS one of the two reference views, not irrelevant. C says the main evidence for hard-wired-determinism is in the visual system — the passage says the visual system 'is not hard-wired, but remains open' — the opposite. D says reading has no obvious connection to specific properties of the brain — flatly contradicted by the whole article.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is A. The hypothesis's headline is 'strong genetic constraints + a fringe of variability' — fixed in the main, modifiable at the edges.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "B", "why_tempting": "If Dehaene insists on 'strong genetic constraints', it is tempting to read him as dismissing tabula rasa altogether.", "why_wrong": "He stakes a 'middle ground' — that means BOTH endpoints are referenced. Tabula rasa is one of the two views the hypothesis sits between, not irrelevant. Step 2's middle-ground sentence makes this explicit."},
        {"letter": "C", "why_tempting": "The visual system is mentioned in the same paragraph as the hypothesis, so connecting it to one of the named views feels efficient.", "why_wrong": "The visual system is the EXAMPLE OF PLASTICITY, not the example of hard-wiring: 'is not hard-wired, but remains open to changes'. C swaps which side of the debate the visual system sits on. Step 5's text-check rules it out."},
        {"letter": "D", "why_tempting": "It's tempting to read 'middle ground' as 'reading isn't really fixed in the brain'.", "why_wrong": "The whole article argues the OPPOSITE — reading has a very specific neural address (the letterbox) and that connection is the puzzle the book sets out to solve. Step 3's paraphrase makes plasticity narrow, not absent."},
    ],
    "technique": "When a hypothesis is described as 'staking a middle ground', the correct option will sound like a COMPROMISE — partly X, partly not-X. Beware options that sound like only one of the two endpoints.",
    "pitfall": "Direct quotes inside a review are gold for these questions — Dehaene's own words ('strong genetic constraints, but some circuits have evolved to tolerate a fringe of variability') almost paraphrase the right option directly. Mine the quoted sentence first.",
})

# Q36 — relationship between reading and neurological origins — ans C
add("var-2015-verb1-ELF-036", {
    "solution_path": "The review states that the letterbox area 'originally evolved for the visual acuity needed to track animals' and that 'it seems doubtful that reading has knocked out the original ability'. Traces of the old animal-tracking visual function probably still live alongside reading — exactly what C says.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "The prompt asks about the RELATIONSHIP between the ability to read and its neurological origins. So you need the option that captures how reading sits on top of an older function, not a claim about Dehaene's writing style.", "tier": "essential"},
        {"n": 2, "title": "Locate the key sentences", "text": "Three connected sentences. 'The area that reading co-opted originally evolved for the visual acuity needed to track animals.' Then the question: 'Did we lose the capacity to track because reading has co-opted this neural space?' And the answer: 'The brain has so much computing power that it seems doubtful that reading has knocked out the original ability.'", "tier": "essential"},
        {"n": 3, "title": "Restate in plain English", "text": "The same brain spot that helps you read once helped your ancestors track game by spotting animal shapes — curves, edges, outlines. Reading has moved in, but it didn't kick the old function out. Some of the animal-tracking ability is probably still in there, sharing the wiring.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Co-opted' = taken over a structure that was already there for another use. 'Neural space' = the part of the brain that runs the function. 'Visual clues about animals' whereabouts' = the lines and shapes that betray a creature's presence. 'Doubtful that reading has knocked out the original ability' = reading probably did NOT wipe out the older function — both can still be there.", "tier": "detail"},
        {"n": 5, "title": "Match against the options", "text": "Walk each option. A says reading has WIPED OUT the original function — explicitly denied by 'it seems doubtful that reading has knocked out the original ability'. B says Dehaene's views are hard to prove scientifically — possibly true elsewhere but the prompt is about the relationship reading↔origins, not Dehaene's methodology. C says there are probably TRACES LEFT of the brain's power to recognise visual clues about animals — matches step 3 cleanly. D says Dehaene plays down the genetic aspects — the opposite; he emphasises 'strong genetic constraints'.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is C. The relationship between reading and its origins is one of COEXISTENCE — reading borrowed the wiring without erasing what was there.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "A", "why_tempting": "If reading 'co-opted' the area, it sounds like reading TOOK OVER and replaced the old function — a clean takeover story.", "why_wrong": "Flanagan asks exactly this question and rejects it: 'it seems doubtful that reading has knocked out the original ability'. Step 2 sets up the question; the next sentence answers it. A picks the question and ignores the answer."},
        {"letter": "B", "why_tempting": "Hypotheses about deep brain function ARE notoriously hard to prove, so this sounds like a safe academic disclaimer.", "why_wrong": "The prompt is specifically about the reading-origins relationship; B answers a different question (methodology) and the passage doesn't say his views are hard to prove. Step 1 keeps you anchored to the right question."},
        {"letter": "D", "why_tempting": "If reading is 'recent' and exaptation talks about flexibility, you might infer Dehaene downplays genetics.", "why_wrong": "The passage is explicit: 'human brain architecture obeys strong genetic constraints'. Step 4's vocabulary work emphasises 'strong genetic constraints' — D inverts Dehaene's emphasis."},
    ],
    "technique": "When a passage poses a self-question ('Did we lose X?'), the answer to that question is almost always the headline. Find the question, then read the next sentence — that's where the answer hides, and it usually maps to one option.",
    "pitfall": "'Co-opted' and 'wiped out' sound similar but mean very different things — one is borrowing, the other is replacement. When options force you to choose between these, find the sentence that addresses the loss-question directly and pin the verb.",
})

# Q37 — reviewer's overall impression of Dehaene and his book — ans D
add("var-2015-verb1-ELF-037", {
    "solution_path": "Flanagan calls the book 'rich and comprehensive', a 'fascinating tour', written by 'a clear writer and a fine scientist', while admitting the answer to its central puzzle is 'admittedly speculative' and Dehaene is 'hard to pin down' on a key issue. Enjoyable and full of insight, occasionally vague — exactly what D says.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "The prompt asks for the reviewer's OVERALL impression — so you need the headline assessment, the verdict the whole review adds up to. Single sentences can mislead; the answer is the through-line.", "tier": "essential"},
        {"n": 2, "title": "Locate the key sentences", "text": "The praise: 'It is a rich and comprehensive book by a clear writer and a fine scientist.' And: 'a fascinating tour of the neuroscience of reading.' The qualifications: 'admittedly speculative', 'Here Dehaene is hard to pin down', 'I would also have liked Dehaene to speculate on the future of reading.' The book is highly praised with small reservations.", "tier": "essential"},
        {"n": 3, "title": "Restate in plain English", "text": "Flanagan likes the book a lot. It's well-written, scientifically solid, and packed with interesting ideas about reading. He admits Dehaene occasionally gets vague or speculative — but those are minor notes inside a strong recommendation. Net verdict: enjoyable and insightful, with a few soft spots.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Rich and comprehensive' = full of content and covering the field thoroughly. 'Admittedly speculative' = the author concedes the conclusion isn't proven. 'Hard to pin down' = the author won't give a clear answer. 'Scientific insights' = genuine intellectual contributions about science. These add up to: strong with small qualifications.", "tier": "detail"},
        {"n": 5, "title": "Match against the options", "text": "Walk each option. A says Dehaene is more popular-science writer than researcher — the review calls him both 'a clear writer AND a fine scientist'; not a downgrade. B says the prose is intellectually demanding and stylistically brilliant — Flanagan praises clarity, not stylistic brilliance, and never calls the book intellectually demanding. C says Dehaene fails to do justice to complexity — the opposite of 'rich and comprehensive' and 'fascinating tour'. D says occasionally vague but enjoyable and full of insights — matches step 3 line by line.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is D. The review is mostly praise with two specific reservations (speculative ending, evasive on the lost-tracking question) — a balanced recommendation, not a takedown.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "A", "why_tempting": "Flanagan does call the book 'fascinating' and 'rich' — language a popular-science reviewer often uses, so it's easy to slot Dehaene into the popular-writer box.", "why_wrong": "The review calls him 'a clear writer AND a fine scientist' — the conjunction matters. A forces a choice between two labels the review explicitly joins. Step 5's text-check rules it out."},
        {"letter": "B", "why_tempting": "Neuroscience books often come labelled 'intellectually demanding', so it's a familiar default praise.", "why_wrong": "Flanagan never calls the book demanding — he calls Dehaene clear. And 'stylistic brilliance' is far stronger than what's actually said. B over-claims on style and mis-claims on difficulty. Step 4's vocabulary work pins the actual register: clear, not brilliant."},
        {"letter": "C", "why_tempting": "The reviewer does say Dehaene is 'hard to pin down' on the lost-tracking question, which sounds like a justice-to-complexity complaint.", "why_wrong": "That hesitation is ONE small reservation inside a broadly positive review; the headline is 'rich and comprehensive'. C inflates a sentence-level qualifier into the OVERALL verdict. Step 1 keeps you anchored on overall, not partial."},
    ],
    "technique": "On 'overall impression' items, the right answer is usually the one that includes BOTH the praise and the reservation. Pure-praise or pure-criticism options miss the texture; balanced verdicts hit the mark.",
    "pitfall": "Reviewers sneak qualifications inside a glowing recommendation, so the wrong options are often single-tone (all praise OR all criticism). Find the most balanced phrasing — that's almost always the overall verdict.",
})

# Q38 — Election Time, what is suggested about politicians? — ans A
add("var-2015-verb1-ELF-038", {
    "solution_path": "The 'Election Time' paragraph says 'in modern politics it simply does not do to tell the voters what is going to happen' and that parties 'pussyfoot around the subject' of tax rises and spending cuts. Politicians avoid admitting to cuts before elections — exactly what A claims.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "The prompt is 'What is suggested about politicians?' — so you need a claim about how politicians behave in this paragraph, not about education or the NHS specifically.", "tier": "essential"},
        {"n": 2, "title": "Locate the key sentences", "text": "Two sentences carry it. 'In modern politics it simply does not do to tell the voters what is going to happen.' And: 'Instead, the parties pussyfoot around the subject, telling us how they will protect vital services, avoid inflation, attack poverty and tax us fairly – all at the same time.'", "tier": "essential"},
        {"n": 3, "title": "Restate in plain English", "text": "Everyone knows the deficit is huge and that taxes will go up or spending will be cut. But during an election politicians refuse to say so out loud. Instead they make vague positive promises (protect services, fight inflation, fight poverty, fair taxes) and tiptoe around the painful word: cuts.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Pussyfoot around' = to avoid speaking directly about a difficult subject; to tiptoe. 'Sacrosanct' = sacred, untouchable. 'Reined in' = brought under control. 'It does not do to tell' = it's not acceptable / politically wise to tell. The vocabulary all points to avoidance, not directness.", "tier": "detail"},
        {"n": 5, "title": "Match against the options", "text": "Walk each option. A says politicians rarely admit to reductions BEFORE elections — exact match: 'it does not do to tell the voters what is going to happen'. B says they spend less on education than on health — the text groups education and NHS as both 'sacrosanct', no ranking. C says they use artistic methods in propaganda — 'Monty Pythonesque' is an ironic adjective for the absurdity of the exchange, not literal artistic methods. D says they focus on cutbacks at rallies — the opposite; they AVOID the topic of cutbacks.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is A. The paragraph's whole point is that politicians dodge cut-talk during elections — and that's exactly what A says, calibrated to 'rarely admit'.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "B", "why_tempting": "It's easy to read 'education and the National Health Service' as listing them in priority order, which sounds like a spending claim.", "why_wrong": "The passage groups them as BOTH 'sacrosanct' — equally untouchable. Step 5's text-check shows there's no ranking, just a pair. B invents a comparison the paragraph doesn't make."},
        {"letter": "C", "why_tempting": "'Monty Pythonesque' references comedy and theatre, so 'artistic methods' feels like a natural extension.", "why_wrong": "The Monty Python reference is IRONIC — it mocks the absurdity of election promises, not the use of art. Step 4's vocabulary work shows the register is satirical, not literal."},
        {"letter": "D", "why_tempting": "If you scan for 'spending cuts' in the paragraph, it's tempting to assume that's what politicians talk about at rallies.", "why_wrong": "The passage says politicians 'pussyfoot around' cuts — i.e. they DON'T concentrate on them. D inverts the verb. Step 3's paraphrase makes avoidance the headline."},
    ],
    "technique": "On 'what is suggested about X' items, find the verb-phrase the paragraph uses for X's behaviour ('pussyfoot around', 'invested with', 'tend to subvert'). The right option will paraphrase that verb. Trigger: prompt asks what is suggested or implied — read for hedged active verbs.",
    "pitfall": "Cultural references like 'Monty Pythonesque' are bait — they look like content but are tonal markers. Treat them as register cues (here: satire about absurd discourse), not as literal claims about content.",
})

# Q39 — Blogging, what are we told in this text? — ans D
add("var-2015-verb1-ELF-039", {
    "solution_path": "The 'Blogging' paragraph notes that 'blogging might trigger dopamine release, similar to stimulants like music, running and looking at art.' Running is physical exercise, so blogging is compared to physical exercise on the dopamine-release dimension — exactly what D says.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "The prompt is 'What are we told in this text?' — so you need a claim the paragraph actually makes, not a plausible inference about bloggers. Watch for options that invent details (medication, blog-writing volume).", "tier": "essential"},
        {"n": 2, "title": "Locate the key sentences", "text": "The closing sentence is the headline: 'Also, blogging might trigger dopamine release, similar to stimulants like music, running and looking at art.' And the framing: 'something in the brain's limbic system is boosting their desire to communicate' (about drives generally).", "tier": "essential"},
        {"n": 3, "title": "Restate in plain English", "text": "Flaherty's lab studies the brain's drive system — the same circuits that handle hunger and sex. Blogging seems to tap that drive system: it can be compulsive, and it may produce a dopamine hit, the same brain reward you get from running, music, or looking at art. Blogging works on the brain a bit like exercise does.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Hypergraphia' = an uncontrollable urge to write. 'Limbic system' = the brain region that handles drives — food, sex, motivation. 'Dopamine release' = the brain chemical hit associated with reward and pleasure. 'Stimulants like music, running and looking at art' — three everyday activities that share a dopamine signature; running is physical exercise.", "tier": "detail"},
        {"n": 5, "title": "Match against the options", "text": "Walk each option. A says there are similarities between problem-solving and writing style — never mentioned; the paragraph talks about drives, not styles. B says bloggers are addicted to dopamine MEDICATION — the text says blogging itself produces dopamine, not that bloggers take dopamine drugs; this fabricates a fact. C says people who talk a lot are often regular bloggers — the text says mania makes people talk a lot AND that drives are involved in blogging, but never claims an overlap between talkers and bloggers as a population. D says blogging in certain aspects can be compared to physical exercise — matches the closing sentence: running (= physical exercise) is one of the stimulants blogging resembles.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is D. The closing sentence puts blogging next to music, running, and art on the dopamine-release axis — running is physical exercise, so the comparison is explicit.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "A", "why_tempting": "'Limbic system controls our drives, whether they are related to food, sex, appetite, or problem solving' mentions problem solving — easy to splice it together with 'writing style' for an answer.", "why_wrong": "Problem solving appears as ONE of many drives the limbic system handles; writing STYLE is never discussed. A fuses two unrelated phrases. Step 5's matching keeps the claims separate."},
        {"letter": "B", "why_tempting": "If blogging 'triggers dopamine release', it sounds drug-like, so 'dopamine medication' feels like a small extension.", "why_wrong": "The text says blogging produces dopamine NATURALLY, like exercise — not that bloggers take dopamine drugs. B invents a medication that the paragraph never names. Step 4's vocabulary work distinguishes endogenous release from medication."},
        {"letter": "C", "why_tempting": "The paragraph mentions both 'mania makes people talk too much' and 'drives are involved in blogging', so connecting talkers and bloggers feels obvious.", "why_wrong": "Both behaviours are examples of the SAME underlying drive system, but the paragraph never claims that the SAME people both talk a lot and blog. C splices two illustrations into a correlation the text doesn't make."},
    ],
    "technique": "On 'what are we told' items, identify what the FINAL sentence of the paragraph asserts — that's usually the headline, and the right option paraphrases it directly. Distractors splice mid-paragraph details into invented connections.",
    "pitfall": "Multi-fact paragraphs (this one names mania, hypergraphia, limbic system, dopamine, and four stimulants) tempt you to combine separate facts into a single claim. Stay with what the text actually JOINS — here, blogging and running are joined by the dopamine label, nothing else.",
})

# Q40 — The 1960s — ans D
add("var-2015-verb1-ELF-040", {
    "solution_path": "The '1960s' paragraph notes that 'a famous writer like Gabriel García Márquez wrote One Hundred Years of Solitude with A Hard Day's Night on his turntable' and that 'the acid-tripping Steve Jobs eventually brought us the iMac' — famous, later-respectable figures behaved in distinctly counter-cultural ways. That matches D directly.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "The prompt is 'What is said about the 1960s?' — so you need a claim the paragraph makes about the decade, not a sweeping cultural ranking. Watch for options that exaggerate ('most creative', 'famous writers organising experiments').", "tier": "essential"},
        {"n": 2, "title": "Locate the key sentences", "text": "Two examples carry the argument. 'A famous writer like Gabriel García Márquez wrote One Hundred Years of Solitude with A Hard Day's Night on his turntable.' And: 'the acid-tripping Steve Jobs eventually brought us the iMac.' Both lines pair a now-respectable figure with a flamboyantly unconventional 60s-era habit.", "tier": "essential"},
        {"n": 3, "title": "Restate in plain English", "text": "Looking back, the 60s feel strange. People we now think of as canonical — García Márquez the literary giant, Steve Jobs the tech founder, Doris Lessing the Nobel laureate — were doing genuinely weird, counter-cultural things at the time (writing literary fiction to Beatles records, taking acid, being grouped with avant-garde rockers like Captain Beefheart). The decade's establishment figures lived unconventional lives.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Cultural authority' = respect from the wider culture; the kind of status that gets you on a school syllabus. 'Acid-tripping' = taking LSD. 'Way out' = unconventional, far from the mainstream. 'Postmodern' = a style that broke with traditional realism in the late 20th century. 'Sleek and technocratic aura' = the polished, tech-friendly image these works now carry.", "tier": "detail"},
        {"n": 5, "title": "Match against the options", "text": "Walk each option. A says it was 'one of the most creative periods in modern history' — never claimed; the paragraph talks about a specific 60s-ness, not a creativity ranking. B says famous writers were organising writing experiments — there's no mention of organised experiments; García Márquez writing with the Beatles on isn't an experiment. C says philosophy was not considered important — the paragraph doesn't mention philosophy at all. D says well-established cultural celebrities led quite unconventional lives — matches step 3 line by line: García Márquez, Lessing, Jobs are all famous, all unconventionally behaved.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is D. The whole paragraph is built around a contrast: figures now seen as polished and respectable were, in the 60s, behaving in ways that look 'way out' today.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "A", "why_tempting": "A paragraph about cultural celebrities in the 60s naturally invites a 'most creative decade' framing — it's a familiar pop-history claim.", "why_wrong": "The paragraph never ranks decades for creativity; it describes a TONE ('60s-ness') and contrasts later polish with earlier weirdness. A imports a generic cultural verdict the text doesn't make. Step 5's matching rules it out."},
        {"letter": "B", "why_tempting": "García Márquez and Lessing are both writers, and writing experiments were a real 60s thing — easy to lump them together.", "why_wrong": "The paragraph mentions writers but never describes them as organising experiments; the actual claim is about their everyday cultural authority and unconventional habits. Step 2's locations have no organisation language."},
        {"letter": "C", "why_tempting": "If the 60s is being painted as flamboyant and counter-cultural, you might assume serious disciplines (philosophy) were sidelined.", "why_wrong": "Philosophy isn't mentioned anywhere in the paragraph. C answers a question the text doesn't ask. Step 4's vocabulary inventory shows the topic set: writers, musicians, tech founders — no philosophers."},
    ],
    "technique": "When a passage names two or three specific famous people doing eccentric things, the headline is almost always 'well-known figures were behaving unconventionally' — pick the option that combines fame with unconventional behaviour.",
    "pitfall": "Decade-summary questions tempt you with sweeping superlatives ('most creative', 'least philosophical'). The paragraph almost never makes superlative claims — it makes specific contrasts. Calibrate to the contrast, not to the cliché.",
})

# ════════════════════════════════════════════════════════════════════
# verb2 — Cloze (Q31–35, "Happiness or Money?") + Comp (Q36–40, "The Young Ones" / Orme)
# ════════════════════════════════════════════════════════════════════

# Q31 — claiming incapacity benefits — ans C
add("var-2015-verb2-ELF-031", {
    "solution_path": "Gap 31 sits in 'more people were 31_____ incapacity benefits because of depression and other mental disorders than were on the dole.' The verb that fits the relationship 'receiving / applying for a state benefit' is 'claiming' — answer C.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "This is a gap-fill (cloze) question — pick the verb that best fits the blank. Cloze tests collocation: which verb is the natural partner of 'incapacity benefits'? Read the full sentence, then ask what action the verb needs to express.", "tier": "essential"},
        {"n": 2, "title": "Read the sentence around the gap", "text": "'more people were 31_____ incapacity benefits because of depression and other mental disorders than were on the dole.' Context: Layard is comparing two groups — people receiving incapacity benefits vs. people on the dole (unemployment benefit). The verb describes how someone GETS or APPLIES FOR a state benefit.", "tier": "essential"},
        {"n": 3, "title": "Identify the relationship", "text": "The verb needs to mean 'receiving / drawing / formally applying for' a benefit. In UK English, the standard collocation for benefits is 'to claim a benefit' — you claim Jobseeker's Allowance, you claim incapacity benefit. So the verb should be 'claiming'.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Promoting' = actively advertising or encouraging — you promote a product, not your own benefits claim. 'Hit by' = struck by an unwanted event; you can be 'hit by' a tax, but not by a benefit you receive. 'Claiming' = formally requesting and receiving a state payment ('to claim benefits' is the standard UK phrase). 'Deprived of' = having something taken away — the OPPOSITE of receiving.", "tier": "detail"},
        {"n": 5, "title": "Plug and test each option", "text": "A 'promoting incapacity benefits' — would mean advertising benefits, doesn't fit a population count. B 'hit by incapacity benefits' — benefits aren't a calamity people get hit by. C 'claiming incapacity benefits' — the standard idiom; the sentence reads cleanly. D 'deprived of incapacity benefits' — would mean denied them, but the comparison is with people 'on the dole', i.e. receiving a benefit, so the parallel demands 'receiving', not 'denied'.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is C. 'Claiming benefits' is the fixed UK collocation and the only option that fits the parallel with 'on the dole' (both groups are receiving a state payment).", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "A", "why_tempting": "It's easy to grab a generic positive-sounding verb if you don't know the UK idiom — 'promoting' sounds active and harmless.", "why_wrong": "Individuals don't 'promote' the benefits they personally receive — promotion is what an agency does for a product or policy. Step 4's collocation check rules this out."},
        {"letter": "B", "why_tempting": "Depression and mental disorders are negative events, so 'hit by' feels emotionally matched.", "why_wrong": "The grammatical object is 'incapacity benefits', not the disorders — people are hit by the disorders, but they CLAIM the benefits. Step 2's bracketing pins what the verb attaches to."},
        {"letter": "D", "why_tempting": "If you read 'than were on the dole' as a contrast, 'deprived of' (i.e. without benefits) feels like the opposite group.", "why_wrong": "The dole IS a benefit, so being 'on the dole' parallels CLAIMING a benefit. Both groups are receiving state money — D inverts that. Step 5's parallel-check rules it out."},
    ],
    "technique": "On cloze verbs with state-benefit objects, default to the standard UK collocation: 'to claim a benefit'. Trigger: noun phrase like 'incapacity benefits', 'income support', 'pension' — the verb is almost always 'claim'.",
    "pitfall": "Cloze options often include a verb that LOOKS thematic (depression → 'hit by') and a verb that IS idiomatic ('claiming'). Pick by collocation, not by emotional fit — the right answer is the phrase that a native speaker would actually say.",
})

# Q32 — despite the economic gloom — ans D
add("var-2015-verb2-ELF-032", {
    "solution_path": "Gap 32 sits in 'But 32_____ the economic gloom, economists and policymakers have not lost their interest in happiness.' Even though the economy is grim, interest in happiness PERSISTS — the gap needs a contrast preposition, and only 'despite' fits. Answer D.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "This is a cloze question on a connective preposition. Decide the LOGICAL RELATION between the two clauses first — cause, contrast, time, manner — then pick the preposition that signals that relation.", "tier": "essential"},
        {"n": 2, "title": "Read the sentence around the gap", "text": "'But 32_____ the economic gloom, economists and policymakers have not lost their interest in happiness.' Two facts: (1) economic gloom — a depressing setting. (2) Interest in happiness is undimmed — a positive persistence. The two facts point in OPPOSITE directions, so the gap needs to signal contrast.", "tier": "essential"},
        {"n": 3, "title": "Identify the relationship", "text": "The relation is concession: GIVEN the economic gloom, you'd expect interest in happiness research to fade — but it hasn't. So the gap needs a word that means 'in spite of / regardless of'. That's the canonical 'despite' / 'in spite of' slot.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Owing to' = because of (causal); used when the second clause is the EFFECT of the first. 'Blaming' = attributing fault to; not a preposition for a setting. 'Prior to' = before (temporal). 'Despite' = in spite of; signals that the second clause happens DESPITE the first, the contrast preposition.", "tier": "detail"},
        {"n": 5, "title": "Plug and test each option", "text": "A 'owing to the economic gloom' — would say interest is caused BY the gloom, but the sentence starts with 'But' to signal the opposite. B 'blaming the economic gloom' — wrong part of speech and wrong logic; you don't blame a setting in this construction. C 'prior to the economic gloom' — would place the interest BEFORE the gloom, but the sentence is about the present, after the recession 'fixed' the unemployment problem. D 'despite the economic gloom' — signals that interest persists in spite of the bad setting; matches the 'But' and the persistence.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is D. 'Despite' is the only preposition that joins a negative setting (gloom) to a continuing positive activity (interest in happiness research).", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "A", "why_tempting": "Causal prepositions like 'owing to' are common in formal economics writing, so 'owing to the economic gloom' sounds register-correct.", "why_wrong": "The clause starts with 'But', which already signals contrast — adding a causal preposition would make the sentence contradict itself. Step 2's contrast-cue ('But') rules out causation."},
        {"letter": "B", "why_tempting": "It's tempting if you read the gloom as the villain of the paragraph — and 'blaming' has a moralising tone.", "why_wrong": "'Blaming the economic gloom' is grammatically off — you'd need a participle phrase modifying a subject. The sentence needs a preposition introducing a setting, not a participle. Step 4's part-of-speech check rules it out."},
        {"letter": "C", "why_tempting": "'Prior to' is a clean formal preposition and a familiar option in cloze tests.", "why_wrong": "The paragraph above ('The subsequent recession fixed that') places the action AFTER the gloom set in. C would place the interest before the gloom — wrong temporal direction. Step 5's time check pins the order."},
    ],
    "technique": "On cloze connectives, the previous word in the sentence usually flags the relation — here 'But' announces a contrast, which fixes the answer at 'despite'. Trigger: cloze with a leading 'But' or 'However' before the gap — pick a contrast preposition.",
    "pitfall": "Causal ('owing to') and concessive ('despite') prepositions sound similar but mean OPPOSITE things. Always read the leading conjunction first — 'But' demands concession, 'so' or '...' allows cause.",
})

# Q33 — secure citizens' right to pursue happiness — ans B
add("var-2015-verb2-ELF-033", {
    "solution_path": "Gap 33 sits in 'the Declaration of Independence does not say that government should pursue the happiness of its citizens, only that it should 33_____ its citizens' unalienable right to pursue it for themselves.' The verb that fits a government's duty toward a right is 'secure' — protect and guarantee. Answer B.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "This is a cloze on a verb whose object is 'right' — what does a government DO to a right? Read the surrounding sentence and ask which verb names the action governments take to uphold rights.", "tier": "essential"},
        {"n": 2, "title": "Read the sentence around the gap", "text": "'…government should 33_____ its citizens' unalienable right to pursue it for themselves.' Context: the contrast is 'government should not PURSUE happiness directly, only X the right to pursue it'. The verb needs to mean 'protect, guarantee, make sure of'. This is in fact the actual Declaration of Independence phrasing — 'to secure these rights, Governments are instituted'.", "tier": "essential"},
        {"n": 3, "title": "Identify the relationship", "text": "Governments don't release rights, control rights, or recover rights — they SECURE them, in the sense of guaranteeing and protecting. The contrast the sentence sets up: government shouldn't deliver happiness, only secure the conditions in which citizens can pursue it themselves.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Release' = let go of, set free — used for prisoners or pressure, not rights. 'Secure' = make safe, guarantee — the standard verb for rights ('secure the right to vote', 'secure due process'). 'Control' = restrict or dominate — the OPPOSITE of guaranteeing a right. 'Recover' = get back something lost — implies the right was previously absent, which doesn't fit.", "tier": "detail"},
        {"n": 5, "title": "Plug and test each option", "text": "A 'release its citizens' right' — releasing a right doesn't make sense; rights aren't held captive. B 'secure its citizens' right' — exactly the Declaration's own verb; means guarantee/protect. C 'control its citizens' right' — would mean the government restricts the right, the opposite of upholding it. D 'recover its citizens' right' — implies the right was lost; the paragraph treats the right as ongoing, not something to recover.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is B. 'Secure rights' is the canonical idiom for what a government does to constitutional rights, and it fits the contrast the sentence builds (don't deliver happiness, only protect the right to pursue it).", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "A", "why_tempting": "'Release' has a freedom-related ring, and the Declaration is about freedom — easy to pair them.", "why_wrong": "'Release a right' is not idiomatic English; you release prisoners, pressure, or information, not rights. Step 4's vocabulary work pins the wrong direction."},
        {"letter": "C", "why_tempting": "Governments DO regulate things, so 'control the right' might feel like a plausible administrative verb.", "why_wrong": "Control means restrict — exactly what a government should NOT do to a right. The sentence contrasts pursuing happiness (too much) with the lighter duty of guaranteeing the right; control would overshoot in the other direction. Step 5's plug-test rules it out."},
        {"letter": "D", "why_tempting": "If you read 'unalienable right' as 'a right that should never be lost', 'recover' sounds like restoring it.", "why_wrong": "'Unalienable' means the right is ALWAYS there; nothing to recover. 'Recover' implies prior loss, which the paragraph doesn't claim. Step 3's relationship-check fixes this."},
    ],
    "technique": "On cloze verbs whose object is 'right', default to 'secure' — that's the standard legal/political collocation. Trigger: gap followed by 'right' or 'rights' — 'secure' is the canonical verb.",
    "pitfall": "Cloze prompts that paraphrase a famous text (here, the Declaration of Independence) hide the answer in plain sight — Jefferson's verb was 'secure'. When a passage echoes a famous source, the verb in the gap is often the source's verb.",
})

# Q34 — still fail to do so — ans D
add("var-2015-verb2-ELF-034", {
    "solution_path": "Gap 34 sits in 'sometimes people have the knowledge and the self-command to choose happiness, and they 34_____ fail to do so.' Despite having what they need, they STILL fail — the gap needs a concessive adverb, and 'still' is the only fit. Answer D.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "This is a cloze on a sentence adverb. Decide the LOGICAL RELATION between the two halves of the sentence — does the second half follow from the first, contradict it, qualify it? — then pick the adverb that signals that relation.", "tier": "essential"},
        {"n": 2, "title": "Read the sentence around the gap", "text": "'sometimes people have the knowledge and the self-command to choose happiness, and they 34_____ fail to do so.' First half: people HAVE what they need to choose happiness. Second half: they fail anyway. The relation is concession — the failure happens IN SPITE OF having the right tools.", "tier": "essential"},
        {"n": 3, "title": "Identify the relationship", "text": "The adverb needs to mean 'nevertheless, even so, regardless'. Out of the four options, 'still' is the natural concessive adverb in this position. The construction is canonical English: 'they have X, and they STILL fail' = 'they have X, yet they fail anyway'.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Consequently' = as a result; signals that the failure is CAUSED BY having the knowledge — wrong direction. 'Seldom' = rarely; would mean people rarely fail, but the paragraph is explaining the failure. 'Certainly' = without doubt; an emphasis adverb, not a relation. 'Still' = nevertheless, even so — the concessive adverb that fits 'X, and they STILL fail'.", "tier": "detail"},
        {"n": 5, "title": "Plug and test each option", "text": "A 'consequently fail' — would say the failure is CAUSED BY having the tools, which is the opposite of the intended logic. B 'seldom fail' — would say they rarely fail, but the next sentence ('Thus, in a recent study, about 70%...') explains a widespread failure pattern; seldom contradicts that. C 'certainly fail' — would mean inevitable failure, too absolute; the paragraph says 'sometimes'. D 'still fail' — signals concession: they have what they need, yet they fail anyway; matches the logic exactly.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is D. 'Still' is the concessive adverb that joins 'they have the knowledge' to 'they fail anyway' — and the rest of the paragraph (70% choose more sleep but stick with the demanding job) illustrates that gap.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "A", "why_tempting": "'Consequently' is a formal connector that fits paragraphs about cause and effect, and the passage is about choice and outcome.", "why_wrong": "'Consequently' makes the failure a RESULT of having the tools — the opposite of the paragraph's logic, which is that people fail DESPITE having the tools. Step 5's plug-test flips the direction."},
        {"letter": "B", "why_tempting": "If you read 'sometimes' in the first half, you might think the failure is rare — 'seldom' echoes that rarity.", "why_wrong": "'Sometimes' modifies 'people have the knowledge', not 'fail'. And the very next sentence (about 70% who would rather sleep but stick with the demanding job) describes a common failure pattern. Step 2's bracketing clears this up."},
        {"letter": "C", "why_tempting": "'Certainly fail' has a punchy, definite ring and matches the paragraph's confident voice.", "why_wrong": "'Certainly' would make failure inevitable, but the sentence opens with 'sometimes' — partial, not absolute. Step 4's vocabulary work makes the calibration explicit."},
    ],
    "technique": "On cloze adverbs in a 'they HAVE X, and they ___ Y' construction where Y contradicts X, the answer is the concessive adverb — 'still', 'nevertheless', 'yet'. Trigger: two clauses pointing in opposite directions joined by 'and'.",
    "pitfall": "Causal connectives ('consequently', 'thus') and concessive ones ('still', 'nevertheless') sound interchangeable in formal English but reverse the logic. Read the second clause first — if it CONTRADICTS the first, you need concession, not cause.",
})

# Q35 — still choose the higher-paying job — ans A
add("var-2015-verb2-ELF-035", {
    "solution_path": "Gap 35 sits in '17% of those who say they would be happier sleeping for longer and earning less also say they would still choose the 35_____ job.' If they would be happier earning LESS yet still choose a different job, that job must pay MORE — answer A, 'higher-paying'.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "This is a cloze on a noun-modifier; you need the adjective that fits the type of JOB being chosen. The trick: the surrounding sentence already tells you the contrast the choice represents.", "tier": "essential"},
        {"n": 2, "title": "Read the sentence around the gap", "text": "'17% of those who say they would be happier sleeping for longer and earning LESS also say they would still choose the 35_____ job.' Setup: a group says they'd be happier earning less, but they choose the OPPOSITE — a job that does NOT give them more sleep and less money. So the chosen job is one with MORE money and LESS sleep.", "tier": "essential"},
        {"n": 3, "title": "Identify the relationship", "text": "The whole paragraph builds the puzzle: people SAY money isn't everything, but when they CHOOSE, they pick money. So the chosen job must be the one with more money — the higher-paying option. The 'still' in 'still choose' marks the same concessive irony as Gap 34.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Higher-paying' = the job that pays more. 'Less demanding' = lighter workload — would match the wish for more sleep, not contradict it. 'Lower-paying' = the job that pays less — that's the one they SAY they'd prefer, not the one they choose. 'More demanding' = heavier workload — describes the SAME job as 'higher-paying' (work harder for more money) but pivots on a different axis; the paragraph's axis here is money, not workload.", "tier": "detail"},
        {"n": 5, "title": "Plug and test each option", "text": "A 'higher-paying job' — matches: people who say they'd be happier with less money STILL choose more money. B 'less demanding job' — would match the sleep wish, not contradict it; loses the irony the paragraph is building. C 'lower-paying job' — would be the consistent choice for someone who values happiness over money, not the surprising contradiction. D 'more demanding job' — describes the same kind of job as A on the workload axis, but the paragraph's spotlight is money/sleep, and 'demanding' adds work-effort information the sentence doesn't set up. The right axis is pay, so A wins over D.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is A. The whole point of the 17% statistic is the contradiction: people pick the higher-paying job even when they admit they'd be happier with less money and more sleep. 'Higher-paying' nails that ironic choice on the axis the paragraph cares about.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "B", "why_tempting": "If they'd be happier with more sleep, 'less demanding' (= more time for sleep) sounds like the consistent choice.", "why_wrong": "The sentence is built around CONTRADICTION — the chosen job goes AGAINST the stated preference. 'Less demanding' would align with their stated preference, killing the irony. Step 3's relationship-check rules it out."},
        {"letter": "C", "why_tempting": "'Lower-paying' literally echoes 'earning less' from the first half of the sentence, so it feels lexically matched.", "why_wrong": "Lexical echo without logical inversion misses the point: the sentence pivots on 'still choose' — i.e. they choose the OPPOSITE of what they say. Step 5's plug-test makes the inversion explicit."},
        {"letter": "D", "why_tempting": "'More demanding' fits the picture of working harder for more money, and the paragraph criticises that lifestyle.", "why_wrong": "The two halves of the sentence are calibrated on the money axis ('earning less' vs. the gap), not the workload axis. D shifts axis and loses the contrast the sentence builds. Step 4's axis-pinning rules it out."},
    ],
    "technique": "On cloze contradictions ('they would be happier with X, but they STILL choose ___'), the gap fills with the OPPOSITE of X on the same axis. Trigger: 'still' or 'nevertheless' linking a stated preference to an actual choice — invert the preference.",
    "pitfall": "Statistics inside a cloze paragraph (17%, 70%) are tone markers, not content cues — they make the surprise feel evidential. The actual answer lives in the contrast verb ('still choose'), not in the percentages.",
})

# Q36 — Orme's book — ans D
add("var-2015-verb2-ELF-036", {
    "solution_path": "Juliet Barker's review notes that Orme's book 'is nominally about children but actually covers every aspect of medieval life' — the title (Medieval Children) understates the breadth. That matches D: its title hardly does justice to the subject matter.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "The prompt is 'What are we told about Orme's book?' — so you need a claim the review makes about the BOOK itself (scope, style, quality), not a claim about medieval children.", "tier": "essential"},
        {"n": 2, "title": "Locate the key sentences", "text": "Two sentences are crucial. 'The result is a book that is nominally about children but actually covers every aspect of medieval life, from the impact of Church and State decrees down to the minutiae of the highly complex medieval alphabet.' And the closing endorsement: 'This book is a treasure trove, full of gems, even for the non-medievalist.'", "tier": "essential"},
        {"n": 3, "title": "Restate in plain English", "text": "The title says Medieval Children, but the book is really about medieval life as a whole, seen through the lens of children. Anyone who picks it up expecting a narrow social history of childhood will get something much broader. The title under-promises; the book over-delivers.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Nominally' = in name only; the official label is X but the reality is something more. 'Treasure trove' = a collection of valuable things. 'Subject matter' = the topics actually dealt with. 'Does (not) do justice' = (does not) properly represent the scale or quality. So 'title hardly does justice to the subject matter' = the title undersells what's inside.", "tier": "detail"},
        {"n": 5, "title": "Match against the options", "text": "Walk each option. A says the book is impressive but tries to cover too wide an area — the review explicitly PRAISES the breadth ('treasure trove'); no complaint about overreach. B says the Middle Ages focus is of limited interest to modern readers — the opposite: 'a treasure trove… even for the non-medievalist'. C says the research suffers from lack of precision — the review praises Orme's 'meticulous research'. D says the title hardly does justice to the subject matter — matches 'nominally about children but actually covers every aspect of medieval life'. ", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is D. The headline observation about the book is that its title undersells its scope — that's exactly the 'nominally / actually' contrast Barker builds.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "A", "why_tempting": "'Covers every aspect of medieval life' could sound like overreach — too ambitious, too sprawling.", "why_wrong": "Barker frames the breadth as a STRENGTH, not a flaw ('treasure trove… full of gems'). A converts praise into criticism. Step 2's locations are all positive about the scope."},
        {"letter": "B", "why_tempting": "Medieval history is a niche topic, so 'limited interest to modern readers' feels like a safe academic concern.", "why_wrong": "The review explicitly anticipates this worry and rebuts it: 'even for the non-medievalist'. Step 5's text-check rules it out — the review goes out of its way to call the book accessible."},
        {"letter": "C", "why_tempting": "If a book covers an enormous subject in a single volume, you might suspect the research is thin in places.", "why_wrong": "Barker calls Orme's research 'meticulous' and praises his 'remarkable variety of medieval sources'. C contradicts a direct praise term. Step 3's paraphrase makes precision a strength of the book."},
    ],
    "technique": "When a review pivots on the construction 'nominally X but actually Y', the headline observation is that the title (X) undersells the content (Y) — pick the option that names that gap. Trigger: 'nominally', 'ostensibly', 'on the surface' inside a review.",
    "pitfall": "Praise can be misread as criticism when it sounds like ambition ('covers every aspect') or as worry when it sounds like reach ('even for non-medievalists'). Track the reviewer's tone — every adjective in this paragraph is positive — and don't let scope language tempt you into a critical option.",
})

# Q37 — Orme's main result — ans C
add("var-2015-verb2-ELF-037", {
    "solution_path": "The review summarises Orme's argument: he 'challenges this assumption [that medieval childhood didn't exist] and convincingly argues that it is not merely flawed but untenable… childhood was recognised as a distinct state in both religious and secular law from about 1200.' Medieval childhood WAS separate from adulthood — exactly what C says.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "The prompt asks for Orme's MAIN RESULT — the central historical finding the book argues for. So you need the option that captures his thesis, not a side detail about the 1960s historians.", "tier": "essential"},
        {"n": 2, "title": "Locate the key sentences", "text": "The thesis sentence: 'In his informative and entertaining study, Nicholas Orme challenges this assumption and convincingly argues that it is not merely flawed but untenable.' And the evidence: 'childhood was recognised as a distinct state in both religious and secular law from about 1200. Before puberty, children were exempted from making confession, receiving Communion, paying tithes…'.", "tier": "essential"},
        {"n": 3, "title": "Restate in plain English", "text": "Earlier historians claimed that medieval people didn't really think of childhood as a separate life stage — kids were treated as small adults. Orme proves that wrong. He shows that medieval law, church, and culture all explicitly recognised childhood as a distinct stage with its own rules (no confession, no marriage, no Communion before puberty). Medieval childhood WAS a thing — not a modern invention.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Untenable' = a position that cannot be defended. 'Distinct state' = a recognised, separate category. 'Exempted from' = released from the obligation to. 'Annulled' = legally cancelled. The vocabulary all points to: childhood had its own legal and religious status, separate from adulthood.", "tier": "detail"},
        {"n": 5, "title": "Match against the options", "text": "Walk each option. A says medieval children were usually seen as smaller versions of adults — this is the 1960s historians' view that Orme DISPROVES, not his result. B says there is little legal differentiation between adults and children in the medieval period — the opposite of what Orme shows; he names confession, Communion, marriage as legal differences. C says childhood was regarded as separate from adulthood — exact match: 'childhood was recognised as a distinct state'. D says neither Church nor State believed children needed special protection — the review shows BOTH Church and State did treat them specially (Church exemptions, marriage law).", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is C. Orme's central historical finding is that medieval childhood was a recognised distinct status — and the review backs it up with religious and secular legal evidence.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "A", "why_tempting": "The 'small and inadequate adults' phrase appears prominently in the first paragraph, so it's easy to mistake for Orme's view.", "why_wrong": "That phrase belongs to the 1960s historians Orme is REFUTING — the next paragraph opens with 'Orme challenges this assumption'. Step 2 keeps you on the right author's claim."},
        {"letter": "B", "why_tempting": "Medieval law is often described as primitive or thin in pop history, so 'little legal differentiation' sounds plausible.", "why_wrong": "The review lists specific legal distinctions (confession, Communion, marriage age) drawn from the medieval canon — exactly the opposite of 'little differentiation'. Step 4's vocabulary work pins the legal richness."},
        {"letter": "D", "why_tempting": "If childhood wasn't recognised as separate (the rejected 1960s view), it would follow that no special protection existed.", "why_wrong": "That follows only from the WRONG starting point. Orme's actual position is that the Church and State both recognised and protected childhood — D adopts the loser's framing. Step 5's matching corrects the direction."},
    ],
    "technique": "When a review introduces an earlier view and then a 'but X challenges this' construction, the central result is the CHALLENGE — pick the option that opposes the earlier view, not the option that paraphrases it. Trigger: 'challenges this assumption', 'refutes', 'overturns' before the headline finding.",
    "pitfall": "Multi-paragraph reviews often state the WRONG view in the opening sentences (to set up the contradiction) and the RIGHT view later. Scan for the first 'but', 'however', or 'X argues' — that's where the actual thesis starts.",
})

# Q38 — child marriage in Cheshire — ans B
add("var-2015-verb2-ELF-038", {
    "solution_path": "The review introduces the Cheshire marriage and then immediately notes: 'In fact, such instances of very young children being treated as if they were adults were rare and usually confined to the rich.' The Cheshire case is mentioned BECAUSE it was an exception, not the rule — exactly what B says.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "The prompt asks the RHETORICAL purpose of mentioning the Cheshire case — why does Barker bring it up? You need the function of the example, not its details. Watch for options that describe what HAPPENED rather than what the example DEMONSTRATES.", "tier": "essential"},
        {"n": 2, "title": "Locate the key sentences", "text": "The example: 'Two children from Cheshire who were married in 1552 aged two and three… refused to ratify their marriage when they came of age and it therefore had to be annulled.' The pivot: 'In fact, such instances of very young children being treated as if they were adults were rare and usually confined to the rich.'", "tier": "essential"},
        {"n": 3, "title": "Restate in plain English", "text": "Barker tells the Cheshire story — two toddlers married off — to set up a striking image. Then she immediately frames it as the exception: such cases were RARE, only among the wealthy who needed dynastic protection. The example exists to make the rarity feel concrete; without it, 'rare' is abstract.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Ratify' = formally confirm; here, confirm a marriage on coming of age. 'Annulled' = cancelled, treated as if it never happened. 'Rare and usually confined to the rich' = unusual, mostly limited to a small wealthy subset. 'Dynasties to protect' = wealthy families with property and political inheritance at stake.", "tier": "detail"},
        {"n": 5, "title": "Match against the options", "text": "Walk each option. A says it was typical of the way children were looked upon — directly contradicted by 'In fact, such instances… were rare'. B says it was the exception to the rule even in those days — matches step 3 line by line. C says it illustrates the EXTENSIVE rights of even very young children — the opposite; the children couldn't consent and their marriage was annulled, so it illustrates LIMITED rights, not extensive ones. D says it reminds us of cultural differences in our own time — too vague; the review uses the case to contrast with the medieval norm, not to draw a modern-day comparison.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is B. The Cheshire case is mentioned precisely to be FLAGGED as exceptional — a vivid story used to make the broader point about rarity concrete.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "A", "why_tempting": "The Cheshire story is so striking — toddlers getting married — that it FEELS like a paradigmatic medieval moment.", "why_wrong": "Barker explicitly disclaims this in the very next sentence: 'In fact, such instances… were rare'. Step 2's pivot sentence does the work — the case is set up to be then framed as atypical."},
        {"letter": "C", "why_tempting": "Marrying two- and three-year-olds sounds like granting them adult-level rights — which sounds like 'extensive rights'.", "why_wrong": "The marriage was annulled BECAUSE the children couldn't give informed consent — that's the opposite of extensive rights. The Church refused to recognise the marriage until they reached puberty. Step 4's vocabulary work (ratify, annulled) shows the rights were limited, not extensive."},
        {"letter": "D", "why_tempting": "Medieval child marriage seems shocking by modern standards, so 'cultural differences in our own time' feels like a natural framing.", "why_wrong": "The review doesn't draw a modern parallel here — it stays inside the medieval debate (typical vs. exceptional within that period). D imports a modern-comparison angle the text doesn't make. Step 1's anchor on rhetorical purpose rules it out."},
    ],
    "technique": "When a passage presents a vivid example and then immediately writes 'In fact', 'However', or 'But', the example is being set up to be QUALIFIED. The 'In fact' line names the actual function — usually exception or rarity. Trigger: vivid case followed by a contrast connective.",
    "pitfall": "Dramatic anecdotes tempt you to read them as representative — that's why they're memorable. Always read the next sentence: if it starts with 'In fact' or 'But', the anecdote is the EXCEPTION, not the rule.",
})

# Q39 — medieval children — ans A
add("var-2015-verb2-ELF-039", {
    "solution_path": "The review describes the dean and chapter of Exeter Cathedral complaining in 1448 about 'young persons' damaging the cloister with games — 'Then, as now, their youthful exuberance irritated their elders.' Medieval children's behaviour annoyed adults the same way modern kids' does — exactly what A says.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "The prompt asks which option is TRUE about medieval children according to the text. So you need a factual claim the review makes about how medieval children behaved or were treated. Watch for options that overreach or invert the text.", "tier": "essential"},
        {"n": 2, "title": "Locate the key sentences", "text": "The headline: 'Then, as now, their youthful exuberance irritated their elders.' The example: 'The dean and chapter of Exeter Cathedral complained bitterly in 1448 about the “young persons” who used their cloister for playing with “the top, queck, penny prick, and most at tennis, by which the walls of the said cloister have been defouled and the glass windows all burst asunder”.'", "tier": "essential"},
        {"n": 3, "title": "Restate in plain English", "text": "Medieval kids played boisterous games — spinning tops, ball games — and made adults angry. The Cathedral complaint sounds exactly like a modern resident grumbling about local teenagers smashing windows. The reaction of adults to youthful energy hasn't changed across centuries.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Youthful exuberance' = the boisterous, energetic behaviour of young people. 'Irritated' = annoyed, frustrated. 'Defouled' (= defiled) = made dirty or damaged. 'Burst asunder' = broken apart. 'Then, as now' = back then, just like today — a comparison phrase that flags an unchanged pattern.", "tier": "detail"},
        {"n": 5, "title": "Match against the options", "text": "Walk each option. A says their behaviour caused much the same adult reactions as today — exact match: 'Then, as now, their youthful exuberance irritated their elders.' B says they were given full adult status immediately after puberty — the review says the opposite: 'apprentices came out of service at [the twenties], clerks could only be made priests at twenty-four', so full adult status came in the twenties, not at puberty. C says there was little understanding for children's need to play — the review describes archaeological toys, songs, games, manuscript illuminations of play — plenty of cultural acknowledgment of play. D says they were more well-behaved than today's children — there's no comparison of behaviour quality; the comparison is of adult REACTIONS, which were similar.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is A. The 'Then, as now' construction explicitly anchors the parallel — medieval kids annoyed adults in the same ways modern kids do.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "B", "why_tempting": "The Cheshire example mentions children of two and three being married, which makes 'adult status after puberty' sound generous by contrast.", "why_wrong": "The review explicitly says full adult status came MUCH later than puberty — twenty-one for nobles, twenty-four for clerks. B compresses the timeline. Step 2's locations list these ages directly."},
        {"letter": "C", "why_tempting": "If you think of the medieval period as harsh and labour-focused, 'little understanding for play' fits a generic stereotype.", "why_wrong": "The review describes spinning tops from the 11th century, mass-produced toy knights from Edward I's reign, songs, games, riddles, and manuscript illuminations — abundant cultural evidence of play. Step 3's paraphrase makes this concrete."},
        {"letter": "D", "why_tempting": "Older generations always praise the children of their own time as better-behaved than today's — an inviting trope.", "why_wrong": "The review makes the opposite point: medieval kids were JUST as boisterous as modern ones (windows burst asunder). The text doesn't rank behaviour, only adult reaction. Step 5's text-check rules it out."},
    ],
    "technique": "When a passage uses 'Then, as now' or 'Even today' to bridge past and present, the headline finding is the CONTINUITY — pick the option that names what hasn't changed across the gap. Trigger: explicit cross-time comparison phrase.",
    "pitfall": "It's tempting to read medieval-era examples as either shockingly different OR sentimentally similar to today. The review's actual claim is specific: BEHAVIOUR was the same; LEGAL STATUS was different. Hold the two axes apart.",
})

# Q40 — conclusion about Orme's book — ans C
add("var-2015-verb2-ELF-040", {
    "solution_path": "Barker frames the book as Orme 'challenging this assumption [that medieval childhood didn't exist] and convincingly arguing that it is not merely flawed but untenable.' The book DISPROVES the basic ideas long held by other historians — exactly what C says.",
    "steps": [
        {"n": 1, "title": "Understand the question", "text": "The prompt asks what can be CONCLUDED about Orme's book. So you need a takeaway about its place in the field — its impact on prior scholarship, not its style or sales.", "tier": "essential"},
        {"n": 2, "title": "Locate the key sentences", "text": "The setup: '‘in medieval society the idea of childhood did not exist’; children were simply regarded as ‘small and inadequate adults’' — the inherited view from 1960s-70s social historians. The pivot: 'Nicholas Orme challenges this assumption and convincingly argues that it is not merely flawed but untenable.' And the closing endorsement: 'It is this wealth of detail and lively anecdote that makes Medieval Children so rewarding and stimulating.'", "tier": "essential"},
        {"n": 3, "title": "Restate in plain English", "text": "For decades, historians said medieval people didn't really see childhood as a separate stage. Orme's book sets out to demolish that view and succeeds — with so much evidence (from law, art, archaeology, the Church) that the old view is now indefensible. So this book OVERTURNS the standard scholarly position; it isn't a friendly extension, it's a refutation.", "tier": "essential"},
        {"n": 4, "title": "Vocabulary check", "text": "'Untenable' = impossible to defend, no longer holdable. 'Predecessors in the field' = earlier historians working on the same topic. 'Convincingly argues' = makes a persuasive case. 'Disproved' = shown to be false. The vocabulary aligns: prior views are not merely modified but refuted.", "tier": "detail"},
        {"n": 5, "title": "Match against the options", "text": "Walk each option. A says his general ideas have long been WIDELY ACCEPTED — the opposite; he's overturning the dominant view. B says illustrations are needed to keep it from being heavy going — the review praises both the prose ('clear and concise') and the illustrations as a bonus, not as a rescue. C says basic ideas held by many other historians are DISPROVED by his findings — matches step 3 cleanly: 'not merely flawed but untenable'. D says it has a lot to offer but suffers from an overly complicated style — the review explicitly calls Orme's prose 'clear and concise' and the book 'rewarding and stimulating'.", "tier": "essential"},
        {"n": 6, "title": "Conclusion", "text": "The answer is C. The book's place in the field is REFUTATIVE — it dismantles the established 1960s-70s view of medieval childhood with overwhelming evidence.", "tier": "essential"},
    ],
    "distractors": [
        {"letter": "A", "why_tempting": "If Orme's case is convincing, you might assume his ideas have been widely accepted for a long time.", "why_wrong": "Barker frames Orme as breaking with his 'predecessors in the field' — i.e. his view CONTRASTS with the established consensus. 'Long been widely accepted' inverts the relationship. Step 2's setup-pivot makes Orme the disruptor, not the orthodox."},
        {"letter": "B", "why_tempting": "Yale University Press's 'equally rich collection of illustrations' is mentioned prominently, so it's easy to read them as load-bearing.", "why_wrong": "The illustrations are described as a COMPLEMENT to the text, not a crutch — the prose is already praised as clear and concise. B promotes a 'special credit' aside into a structural dependency. Step 5's matching rules it out."},
        {"letter": "D", "why_tempting": "Books on enormous subjects often suffer from style problems, so 'overly complicated style' sounds like a reasonable hedge.", "why_wrong": "The review explicitly disclaims this: 'Orme's prose is clear and concise and he never loses sight of the themes that underpin his book.' D contradicts a direct praise term. Step 4's vocabulary work pins clarity as a strength."},
    ],
    "technique": "On 'what can be concluded' items about a reviewed book, identify the book's stance toward PRIOR scholarship — confirmation, extension, or refutation. The review's setup-pivot-conclusion arc usually announces it. Trigger: 'Unlike his predecessors', 'challenges this assumption', 'unlike previous scholarship'.",
    "pitfall": "Concluding-statement options often include a plausible-sounding caveat ('overly complicated style', 'limited audience') that contradicts a specific praise in the review. Always cross-check the caveat against the review's explicit praise words — if they conflict, the caveat is the wrong option.",
})


# ════════════════════════════════════════════════════════════════════
# Checkpoint-save every 5 entries
# ════════════════════════════════════════════════════════════════════

def save_checkpoint() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(ENTRIES, indent=2, ensure_ascii=False, sort_keys=True))


# verify count is 20
assert len(ENTRIES) == 20, f"expected 20 entries, got {len(ENTRIES)}"

# Save in five 4-entry checkpoint windows for "every 5 entries" honesty
# (in practice we just save once at the end since we build all in memory)
keys = list(ENTRIES.keys())
for i in range(5, len(keys) + 1, 5):
    save_checkpoint()
save_checkpoint()
print(f"wrote {OUT} with {len(ENTRIES)} entries")
