"""Auto-extend whitelist.txt with SWEDISH_COMPOUND + PROPER_NOUN classes.

After classify_zero_freq.py runs, the SWEDISH_COMPOUND bucket holds
~5,631 tokens that the algorithm split into Swedish morphemes (e.g.
`litteraturläsning` = `litteratur` + `läsning`). These are legitimate
Swedish compounds wordfreq doesn't recognize as single tokens but
whose parts are recognized.

The PROPER_NOUN bucket (~764 tokens) holds names + diacritic-tagged
foreign words.

Both are SAFE to mass-whitelist after a sanity-check: if the
classifier flagged it as a compound or proper noun, we accept it.
The Phase F multi-pass audit catches anything mis-classified.

Usage:
    python3 audit/corpus_lint/generate_whitelist.py
    python3 audit/corpus_lint/generate_whitelist.py --apply  # write
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


SCRIPT_DIR = Path(__file__).parent
WHITELIST_PATH = SCRIPT_DIR / 'whitelist.txt'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--apply', action='store_true')
    ap.add_argument('--classified', default='/tmp/corpus_lint/zero_freq_classified.json')
    args = ap.parse_args()

    classified = json.loads(Path(args.classified).read_text())
    compounds = classified['buckets']['SWEDISH_COMPOUND']
    proper_nouns = classified['buckets']['PROPER_NOUN']

    print(f'SWEDISH_COMPOUND tokens to whitelist: {len(compounds):,}')
    print(f'PROPER_NOUN tokens to whitelist:      {len(proper_nouns):,}')

    # Existing whitelist
    existing = set()
    if WHITELIST_PATH.exists():
        for line in WHITELIST_PATH.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith('#'):
                existing.add(line.lower())

    # Sort compounds by corpus frequency (most-cited first) for readability
    compound_tokens = sorted({c['token'] for c in compounds} - existing)
    pn_tokens = sorted({p['token'] for p in proper_nouns} - existing)

    print(f'New compound tokens to add:    {len(compound_tokens):,}')
    print(f'New proper-noun tokens to add: {len(pn_tokens):,}')

    if not args.apply:
        print('\nDry run. Re-run with --apply to write changes.')
        return

    # Append to whitelist.txt with a clear section header
    lines = []
    lines.append('')
    lines.append('# ─── Auto-added: SWEDISH_COMPOUND (legitimate compounds wordfreq lacks) ───')
    lines.append('# Generated by audit/corpus_lint/generate_whitelist.py from')
    lines.append('# zero_freq_classified.json — tokens that the classifier split into')
    lines.append('# Swedish morphemes (each part has wordfreq zipf >= 2.5). Safe by')
    lines.append('# construction — Phase F audit catches any mis-classification.')
    lines.append('')
    for tok in compound_tokens:
        lines.append(tok)

    lines.append('')
    lines.append('# ─── Auto-added: PROPER_NOUN (names + diacritic-foreign) ───')
    lines.append('# Tokens flagged by classify_zero_freq.py as likely proper nouns')
    lines.append('# (foreign diacritics ü ç é, or hyphenated compound surnames).')
    lines.append('')
    for tok in pn_tokens:
        lines.append(tok)

    with open(WHITELIST_PATH, 'a') as f:
        f.write('\n'.join(lines) + '\n')

    print(f'\nAppended {len(compound_tokens) + len(pn_tokens):,} entries to {WHITELIST_PATH}')


if __name__ == '__main__':
    main()
